### ISSUE TITLE
Improve plot_rotor

### ISSUE THREAD

**Issue by atbrandao** [ross-rotordynamics/ross#114]
1. The node number tags are evenly spaced along the rotor plot. They should be placed on top of each respective node, and the nodes are usually not evenly spaced.

2. The X and Y coordinates shoul be on the same scale on the plot, so the user can have an idea of the rotor actual proportions.

3. Depending on the number of nodes, the bearing representation becomes disproportionally large. The bearing representation on plot_rotor should have its axial length based on the length of adjacent elements.

4. Indicate the rotor sections that might be hollow (i_d > 0). The rotor plot currently shows the rotor to be always solid.

**Comment by rodrigomoliveira1** [comment]
Pull Request #117 have been merged.
