### ISSUE TITLE
Benchmark folder

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#137]
I am trying to add doctests to solve issue #84.
One problem that I have found is that when running `pytest --doctest-modules` pytest will try to run doctests inside all files that are placed within the ross directory, including those that are inside the Benchmark directory. If possible, it would be better to have the Benchmark folder in the main repository folder. With this, we also avoid downloading the benchmark folder when installing ross with pip, since the user will not use be using the benchmark script.

Can you take a look at this @GabrielBachmann ?

**Comment by GabrielBachmann** [comment]
PR #138  solves this issue.
