### ISSUE TITLE
fluid_flow code automatically showing plots

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#140]
When running the fluid_flow code, the plots are showing automatically.
We should try only to return the objects and let the users decide if they will plot the results.
For matplotlib, one common way of coding this is the following:
```python
def plot_func(args, ax=None):
    if ax is None:
        # get current axes, if None a new axes is created.
        ax = plt.gca() 
    ...
    ax.plot(...)
    ...
    return ax
```
For bokeh we can return the bokeh figure.

**Comment by flaviorangel** [comment]
As for bokeh, should figure be a parameter as well? Then we wouldn't `show(figure)` in the end of the function. Instead we would `return figure`.
