### ISSUE TITLE
Improvements to examples in the documentation

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#166]
- Enumerate the examples (1, 2, 3, ..., instead of 5.8.1, 5.8.2, ...); 
- insert a brief explanation of the example and indicate the reference;
- Complement the examples with other types of results generated by ROSS
(such as Campbell's diagram, static analysis, etc.).

**Comment by raphaeltimbo** [comment]
I think #174 solved this, so I will close the issue for now.
