### ISSUE TITLE
Implement test for material class

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#17]
Tests are missing for the material class. We need to implement the tests using pytest.

This is a good talk about testing:
[Andrew Knight | Testing is Fun in Python!](https://www.youtube.com/watch?v=Sb2tz9Hlbp8)

A more in-depth tutorial:
[Michael Tom-Wing, Christie Wilson - Introduction to Unit Testing in Python with Pytest - PyCon 2016](https://www.youtube.com/watch?v=UPanUFVFfzY)

**Comment by GabrielBachmann** [comment]
The pull request #30 closes this issue.
