### ISSUE TITLE
Include bokeh plots on documentation

### ISSUE THREAD

**Issue by GabrielBachmann** [ross-rotordynamics/ross#179]
I've found a way to include bokeh plots on sphinx automatically, there's a sphinx extension called nbsphinx that does this. You think we can include that on the documentation @raphaeltimbo ?

**Comment by raphaeltimbo** [comment]
Great! I think it would be a good idea to first run a test with one of the example notebooks. This way we can check if the pros and cons of this tool.

**Comment by GabrielBachmann** [comment]
I've tested the [nbsphinx](https://github.com/spatialaudio/nbsphinx) extension and the outputs can be seen as follows
![image](https://user-images.githubusercontent.com/32821252/61188712-a27e5800-a659-11e9-95af-361e14f653e7.png)
![image](https://user-images.githubusercontent.com/32821252/61188721-bd50cc80-a659-11e9-8019-a97ff2d6e930.png)

**Comment by raphaeltimbo** [comment]
@GabrielBachmann , can you open a pull request for this?

**Comment by GabrielBachmann** [comment]
PR #215 closes this issue.
