### ISSUE TITLE
Issue with line endings

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#18]
In the #8 PR I have noticed that there was a ^M character at the end of some lines:
![image](https://user-images.githubusercontent.com/18506378/51198933-b29cc100-18dc-11e9-9c37-ef02b3ac4b08.png)

It looks like this breaks the diff for the file.

**Comment by rodrigomoliveira1** [comment]
I just found an explaination for this problem: 

"_The ^M is a carriage-return character. If you see this, you're probably looking at a file that originated in the DOS/Windows world, where an end-of-line is marked by a carriage return/newline pair, whereas in the Unix world, end-of-line is marked by a single newline._"

So, i'm removing the line break and leting all the sentence in a same line to avoid it.

**Comment by raphaeltimbo** [comment]
There is also a problem related to line endings on different platforms.
[This article](http://web.archive.org/web/20150912185006/http://adaptivepatchwork.com:80/2012/03/01/mind-the-end-of-your-line/) explains the problem and how to configure git to take care of end of line normalization.

I will add a .gitattributes file to the repository to deal with this issue.
