### ISSUE TITLE
Class element is repeated on different modules

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#19]
The `class Element` is repeated on different files: shaft_element.py, disk_element.py...
I think we should have that class in a separate element.py file and the other modules should import from it.

**Comment by rodrigomoliveira1** [comment]
Sounds good! i'm doing it right now. Just moved the `class Element` to a new element.py and removed it from the orignials ones.

**Comment by rodrigomoliveira1** [comment]
A new file element.py has been added. The commit is [here](https://github.com/ross-rotordynamics/ross/pull/20/commits/e53c436a86118c414b1ce3ebe3eab64b9bab6945)

**Comment by rodrigomoliveira1** [comment]
So, I just commited changes in 3 files removing the `class element` from them. They're listed below:

- [shaft_element.py](https://github.com/ross-rotordynamics/ross/commit/bc534ec07c4eaba36f156cc145efc80379bf7b0d)

- [disk_element.py](https://github.com/ross-rotordynamics/ross/commit/330745446bc27c518e669333657a7adf4e31107d)

- [bearing_seal_element.py](https://github.com/ross-rotordynamics/ross/commit/5f2a75da7b2ac31f59cf3d76475d3786ac6d4009)

They are all together in a new branch called "element_file" including the element.py file
