### ISSUE TITLE
Instantiate shaft from excel file

### ISSUE THREAD

**Issue by GabrielBachmann** [ross-rotordynamics/ross#193]

**Comment by flaviorangel** [comment]
I created a function to instantiate a shaft from a table, either xlsx or csv. It was based on a similar function in the [BearingElement class](https://github.com/ross-rotordynamics/ross/blob/master/ross/bearing_seal_element.py) and a function from an [old version of ross](https://github.com/raphaeltimbo/ross/blob/master/ross/data_io/read_xl.py).

The input table should contain a header with column names equal to parameter names in the ShaftElement class, except for a few optional ones, which can be given when the function is called. It returns a list of shaft elements, one per row in the table. I will create the PR now.
