### ISSUE TITLE
Add medium size bearing to fluid flow

### ISSUE THREAD

**Issue by flaviorangel** [ross-rotordynamics/ross#202]
This issue came from issue #37 being broken into different smaller issues. In order to close it, we need to add a test example (preferably with data collected from a real situation) showing that the results match the expected. Since the pressure in a medium size bearing cannot be analytically calculated, it would be better to have real data to comparece with. If not available, we must think of how to validate the experiment.

**Comment by raphaeltimbo** [comment]
@flaviorangel @JuliaMota 
Do we still have work to do on this issue?

**Comment by JuliaMota** [comment]
We can already calculate pressure, forces and stiffness coefficients for medium bearings (only the damping coefficients are missing as mentioned in issue #261 ). However, we have not yet found a reference that provides input data and results for comparison in the case of the medium bearing.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
We don't have a reference case for medium size, but short and long bearings were solved.
