### ISSUE TITLE
Implement tests for the code

### ISSUE THREAD

**Issue by GabrielBachmann** [ross-rotordynamics/ross#205]
The goal of this issue is to make the tests more efficient, not only cover everything but also with fewer tests as possible, this is the report from coverage.
![image](https://user-images.githubusercontent.com/32821252/61241535-12541780-a71a-11e9-99ea-fb8d33ba6be5.png)

**Comment by raphaeltimbo** [comment]
We have improved our coverage in approximately 6%:
![image](https://user-images.githubusercontent.com/18506378/64118146-69b35300-cd6d-11e9-9641-e8065d90cdf8.png)

The files with lower coverage are bearing_seal_element.py and results.py.
I will close this issue and open 2 separate issues for these two files so we can have a better tracking of this.
