### ISSUE TITLE
Bug in plot_eccentricity() method

### ISSUE THREAD

**Issue by GabrielBachmann** [ross-rotordynamics/ross#214]
I was changing the plots from example_05_05_01 (example 9) to the bokeh version of them.
With the following lines:
`# Plotting the eccentricity `
`my_fluid_flow.plot_eccentricity()`
I've got the following error log:
![image](https://user-images.githubusercontent.com/32821252/61748337-55dffe80-ad76-11e9-9805-f7bf60f83c91.png)

**Comment by flaviorangel** [comment]
I'll check it.

**Comment by flaviorangel** [comment]
I was not able to reproduce the error. I'm getting the plot as it was supposed to happen. This error seems to be related to bokeh. Are you on a different version?

![plot](https://user-images.githubusercontent.com/9659033/61811051-01409000-ae17-11e9-8072-e7b3604203ad.png)

**Comment by GabrielBachmann** [comment]
I've tried updating my bokeh version, and I'm getting the same error...
The version that you are using of ross is the same as in pypi?

**Comment by flaviorangel** [comment]
I was using the latest version on GitHub. How about you?
I updated ross on PyPI

**Comment by flaviorangel** [comment]
I have tried updating bokeh and still could not reproduce the error. Does it happen to you outside jupyter notebook?

**Comment by GabrielBachmann** [comment]
This issue was fixed with the PyPI update, it can be closed.
