### ISSUE TITLE
HoverTool does not work with shaft tapered element

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#218]
HoverTool from Bokeh does not currently work with the glyph used to draw the shaft tapered element (glyph "patch"), according to bokeh website:
![Capturar](https://user-images.githubusercontent.com/45969994/61968303-0f74e480-afae-11e9-830d-b6cd2e7f1310.PNG)

So, the informations about the shaft tapered element will not show up. Only for the shaft element.
I don't know if leaving it this way for now or drawing this element in a different way ("patch" was the most suitable glyph to draw a trapeze).

**Comment by raphaeltimbo** [comment]
What I can see as options to solve this problem:
- Using patches (https://stackoverflow.com/a/53384398) instead of patch.
- Adding a transparent glyph together with the patch so that this transparent glyph will have the information to be displayed by the hover tool.

**Comment by rodrigomoliveira1** [comment]
I did with the first option. The ColumnDataSource becomes a list of a single list but it's ok.

**Comment by rodrigomoliveira1** [comment]
PR #232 closes this issue
