### ISSUE TITLE
Plotting Shaft Tapered Elements

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#219]
I built an example using tapered elements in the shaft ends. And I'd like your opinion about the aesthetics.
The main question here is about the connection between the bearing and the shaft's end. For now, I am positioning (about the vertical axis) according to the mean value of the diameters. Do you agree with it or should it be positioned with the lowest diameter?

![Capturar](https://user-images.githubusercontent.com/45969994/61969127-274d6800-afb0-11e9-99d0-37047299dad6.PNG)

**Comment by raphaeltimbo** [comment]
I am ok with the solution that you provided.
But these cases make me think if we really should be using a square to represent bearings, or if we should simply use springs/dampers to do that.

**Comment by rodrigomoliveira1** [comment]
I'm trying to draw a spring/damper system. I will plot a figure here when I am done, so we can compare the results.

**Comment by atbrandao** [comment]
I believe it is not a big issue for tapered elements, because I can't think of a real rotor in which we have bearing connected to a tapered section of the rotor.

However, I do like the idea of representing the bearing as spring/damper icon better than the current 'square' solution.

**Comment by rodrigomoliveira1** [comment]
Since the shaft tapered element plotting style is ok, I'm opening another Issue (#248) to discuss the bearing plotting style.
