### ISSUE TITLE
Unify from_table methods

### ISSUE THREAD

**Issue by flaviorangel** [ross-rotordynamics/ross#228]
We created different from_table methods for bearings, shafts, and now disks. Except for instantiating each class, the routines are very similar, in some parts they are exact the same. It is a bad programming habit to keep different parts of the code executing the same steps, so we should unify these methods.

**Comment by raphaeltimbo** [comment]
I agree!
My suggestion is that we create a utils.py file and there we could write a function that unifies the repeated code. This function could then be imported in each separate module that will have a `.from_table()` method.
