### ISSUE TITLE
Error in Bearing: "x must be strictly increasing"

### ISSUE THREAD

**Issue by flaviorangel** [ross-rotordynamics/ross#257]
I encountered this error while testing tables. Not only is required that the 'w' parameter is sorted, it must also be strictly increasing, meaning that a decreasing 'w' will cause that error, which is what happened during testing. Sorting parameters in init method can fix this.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
@flaviorangel will verify if this is still an issue.

**Comment by flaviorangel** [comment]
I tested adding a new row to one of our test tables, modifying the frequency (old 'w') so that it wouldn't be a strictly increasing parameter. I could not reproduce the error, so I'm assuming it was somehow solved during the changes we have made.
