### ISSUE TITLE
Static analysis plot size 

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#303]
I think the static analysis plots take too much of a horizontal space on the screen:
![image](https://user-images.githubusercontent.com/18506378/65446410-b0dfb180-de0a-11e9-94d1-833c5436f2be.png)

As we can see from the figure above, the free-body diagram takes all the screen and we still have the shearing force diagram to the side of it.
In my view, our figures should have a good size to be displayed on the jupyter notebook.
For this case maybe we could organize all the figures vertically.
Another approach would be to separate the plots and the user would have to call each plot like `.plot_shearing_force()`.

**Comment by rodrigomoliveira1** [comment]
PR #306 closes this issue
