### ISSUE TITLE
Shaft displacement seems too high on static analysis

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#312]
I was looking at our tutorial and I think the values for displacement on the static analysis seem too high. 
![image](https://user-images.githubusercontent.com/18506378/65718776-a9264400-e07a-11e9-8b44-de1539bf96ce.png)

Can you confirm these values @rodrigomoliveira1 ?

**Comment by rodrigomoliveira1** [comment]
Because it's multiplied by 1000. 
When I removed the units from the plot graphs, I should've removed this too.

It was supposed to convert from meters to milimeters. So, actually the displacement is 0.000746

**Comment by rodrigomoliveira1** [comment]
PR #313 closes this issue
