### ISSUE TITLE
CAMPBELL - General advices for the plot

### ISSUE THREAD

**Issue by leoishimoto** [ross-rotordynamics/ross#326]
1. To provide differentiation in color and legend of the harmonics is desirable.
2. The legend of "Forward", "Mixed" and "Backward" modes should not have any color.
3. The red squares (intersections) should have a legend.
4. An argument to change units (rpm,  Hz), in all 3 axis (log dec or damping factor, Rotor speed and DNF's) is desirable.
5. The previous color map (from red to blue) was better for the visualization.

![image](https://user-images.githubusercontent.com/56034613/66068995-ed0ac480-e524-11e9-8858-12afc3d19f7e.png)

**Comment by rodrigomoliveira1** [comment]
> To provide differentiation in color and legend of the harmonics is desirable.

Ok. Each harmonic will be ploted with a different color and will be displayed on the legend.

> The legend of "Forward", "Mixed" and "Backward" modes should not have any color.

I agree with you, however, bokeh does not offer an attribute in Legend to change the glyph color displayed at the board. The glyphs colors match the renderers. There are several options to change the legend colors after setting a render, but for text, background, border line, etc. Maybe, I find a way using bokeh's javascript.

> The red squares (intersections) should have a legend.

Sure, you are rigth, I'm adding it.

> An argument to change units (rpm, Hz), in all 3 axis (log dec or damping factor, Rotor speed and DNF's) is desirable.

Yes, this is something we need to apply to every other method we have. We'll working on it.

> The previous color map (from red to blue) was better for the visualization.

Bokeh does not offer a continuous palette (256 colors) of Red-to-Blue. Bokeh as a ColorBrewer palette called RdBu, but it has only 11 colors. Actually, I still can implement a 256 RdBu (as matplotlib has) using `colorcet` library, but it needs to be installed and imported.

The Figure below is an example using Bokeh's RdBu[11].
![image](https://user-images.githubusercontent.com/45969994/66139403-c1481700-e5d6-11e9-954b-d35825791fa6.png)

**Comment by raphaeltimbo** [comment]
> > The previous color map (from red to blue) was better for the visualization.
> 
> Bokeh does not offer a continuous palette (256 colors) of Red-to-Blue. Bokeh as a ColorBrewer palette called RdBu, but it has only 11 colors. Actually, I still can implement a 256 RdBu (as matplotlib has) using `colorcet` library, but it needs to be installed and imported.

It is possible to create a bokeh colormap from a matplotlib one as shown in [this SO answer](https://stackoverflow.com/a/49934218/5726899).

```python
from bokeh.colors import RGB
from matplotlib import cm

m_coolwarm_rgb = (255 * cm.coolwarm(range(256))).astype('int')
coolwarm_palette = [RGB(*tuple(rgb)).to_hex() for rgb in m_coolwarm_rgb]
```

**Comment by rodrigomoliveira1** [comment]
> It is possible to create a bokeh colormap from a matplotlib one as shown in this SO answer.

Thanks, @raphaeltimbo! it worked just fine.
![image](https://user-images.githubusercontent.com/45969994/66211551-b488f900-e692-11e9-8e2e-aa58640a4a2f.png)

**Comment by rodrigomoliveira1** [comment]
I found an way to display the glyphs with other color at the legend

![image](https://user-images.githubusercontent.com/45969994/66222012-8f9e8100-e6a6-11e9-95d1-0607dc32b0b2.png)

**Comment by rodrigomoliveira1** [comment]
PR #334 closes this issue. It can be re-opened later if something is missing.
The issue about setting units will evaluated later.
