### ISSUE TITLE
"run_static" - Documentation issues

### ISSUE THREAD

**Issue by leoishimoto** [ross-rotordynamics/ross#327]
The description in the documentation of the variables contained in the dictionary does not match with real ones. There are some mismatched capital letters. It would be nice to follow a standard.

![image](https://user-images.githubusercontent.com/56034613/66073831-43c8cc00-e52e-11e9-85cc-48b2dddd745e.png)

Another suggestion is to include units in the dict.
Other possibility is to include all the data directly on the rotor object, without creating a dictionary. I did not understood the logic when an information became a dict or when is attribute to the rotor or to the results of the method.

**Comment by rodrigomoliveira1** [comment]
`force_data` dictionary has been removed.
Now, the following items from `force_data` became Rotor's attributes:
- shaft_weight - Shaft total weight
- disk_forces - Weight forces of each disk
- bearing_reaction_forces - The static reaction forces on each bearing

`Rotor.run_static()` docstring's been updated

**Comment by leoishimoto** [comment]
Just to clarify: Shaft total weight is the sum of the shaft elements or is the rotor (shaft + lumped mass)?
A summary of the rotor is a helpful tool to ensure that are no errors in the model, to perform double checks if the node is the rigth one and so on.

See the example from ROMAC:
![image](https://user-images.githubusercontent.com/56034613/66229894-473c8e80-e6b9-11e9-97d3-762b1ad5bafe.png)

They provide also the global nodes summary (there is a feature to create a automatic discretization of the rotor):

This is the model:
![image](https://user-images.githubusercontent.com/56034613/66230031-9c78a000-e6b9-11e9-868f-e0ad0c31efc8.png)

This is the visualization of the final nodes:
![image](https://user-images.githubusercontent.com/56034613/66229945-6509f380-e6b9-11e9-96a5-c284bf9606c8.png)

XLTRC2 also provides the summary:
![image](https://user-images.githubusercontent.com/56034613/66230212-13ae3400-e6ba-11e9-872e-6939e8facb67.png)


Information as Inertias, CG location, Total length are all useful. I think you can store all of them as attributes, but maybe a method called "summary" that plots something as the two examples above may be a good idea.

**Comment by rodrigomoliveira1** [comment]
> Just to clarify: Shaft total weight is the sum of the shaft elements or is the rotor (shaft + lumped mass)?
A summary of the rotor is a helpful tool to ensure that are no errors in the model, to perform double checks if the node is the rigth one and so on.

The attribute `shaft_total_weight` refers only to the shaft. Maybe it's better adding another attribute called `rotor_total_weight` considering the the shaft + lumped mass to avoid any missunderstanding about it.

> Information as Inertias, CG location, Total length are all useful. I think you can store all of them as attributes, but maybe a method called "summary" that plots something as the two examples above may be a good idea.

It sounds a good idea. For now we have the dataframes built using Pandas. But I think I can organize it using Bokeh widgets and plot like the examples you've said. Thanks for the suggestion.

Soon, I'll come with a preview for what this Bokeh widget will be and we can discuss more about it.

**Comment by rodrigomoliveira1** [comment]
This is a preview of what the summary table will become when it's done.

![image](https://user-images.githubusercontent.com/45969994/66427226-eb8c4100-e9e9-11e9-9f17-202989583d69.png)

It's quite simple to use it (**not implemented yet**):

```
>>> import ross as rs
>>> rotor = rs.rotor_example()
>>> table = rotor.summary().plot()
>>> show(table)
```

We can also create multiples types of summary and organize them in different plot() methods.

**Comment by rodrigomoliveira1** [comment]
I did some improvements to this table. Now we can alternate through tabs to get access to different information. Take a look:

![image](https://user-images.githubusercontent.com/45969994/66680473-03accc00-ec47-11e9-8818-eface4d046ba.png)

![image](https://user-images.githubusercontent.com/45969994/66680493-0efff780-ec47-11e9-952c-242230f7b252.png)

![image](https://user-images.githubusercontent.com/45969994/66680515-1a532300-ec47-11e9-8a4a-ac52574957e3.png)

I've been looking for some way to customize colors, background, fontsize, etc, but to do this, we need to use JavaScript.

**Comment by rodrigomoliveira1** [comment]
PR #342 closes this issue.
