### ISSUE TITLE
Fluid flow code - #TODO

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#35]
[Fluid_flow.py](https://github.com/ross-rotordynamics/ross/commit/6306bbd05afa3d154cfc4bc143dad4cee9b90327) was added in a new branch called "fluid-flow".
Here are some changes that should be made in it.

- Translate comments, names of variables and functions.

- Add docstring to explain functions.

- check PEP 8

- Remove TODO from the code and add them here

**Comment by flaviorangel** [comment]
Comments and names have been translated. The remaining tasks are still pending.

**Comment by flaviorangel** [comment]
These TODOs are commented in the [fluid flow branch](https://github.com/ross-rotordynamics/ross/tree/fluid-flow). They are being solved gradually, but this issue won't be closed until this branch is ready to merge, which will depend mostly on the [example test issue](https://github.com/ross-rotordynamics/ross/issues/37).

**Comment by JuliaMota** [comment]
I checked PEP8 and now it's ok.
Correct documentation details missing.

**Comment by flaviorangel** [comment]
I just pushed changes to the entire fluid-flow code, including those related to these TODOs. I ended up adding a new one: the user needs to be able to choose the structure of the internal radius. I think that belongs to a new issue. This one can be closed as soon as the merges are pushed to the master.

**Comment by JuliaMota** [comment]
Some graphics need proper titles and subtitles
