### ISSUE TITLE
ShaftElement - two methods to load data

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#362]
In the `ShaftElement` class, we have two methods to load data:
- `.load()`
- `.load_data()` (inherited from `Element`)

We need to remove one of these methods.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by rodrigomoliveira1** [comment]
PR #360 fixed this issue.
