### ISSUE TITLE
Error in Campbell Diagram

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#367]
The Campbell diagram for a specific compressor is showing mixed precession for some modes:
![image](https://user-images.githubusercontent.com/18506378/68138434-52c4e480-ff07-11e9-9b1e-a5b3dcdacdff.png)

This is not the correct result.

**Comment by rodrigomoliveira1** [comment]
Try instantiating `Rotor` setting `sparse=False` and check the result again. Maybe it's something about the kappa values when using `scipy.eigs()`. It's only a test to filter out what might be going wrong.
In any case we need to investigate what's causing this problem.

**Comment by raphaeltimbo** [comment]
> Try instantiating `Rotor` setting `sparse=False` and check the result again. Maybe it's something about the kappa values when using `scipy.eigs()`. It's only a test to filter out what might be going wrong.
> In any case we need to investigate what's causing this problem.

Good suggestion. I've tried to check that and the results are the same.
I have noticed some inconsistency between the way the models are being imported from excel. I will double check the model before investigating anything on the Campbell routines.

**Comment by rodrigomoliveira1** [comment]
Well, between having bugs with the campbell diagram and importing from excel, solving the import issue is much simpler.
If you like, send me the example you are trying to run and I can check it out too.

**Comment by raphaeltimbo** [comment]
I confirm that this was an import issue and #374 solves this.
