### ISSUE TITLE
Add book examples to fluid flow code and verify results

### ISSUE THREAD

**Issue by flaviorangel** [ross-rotordynamics/ross#37]
We need to add book examples to fluid flow code to the code instead of the entry data we have now. We also need to verify if the results are according to expected.
Here what needs to be done to close this issue:

[edited on April 7, 2019]:
Short bearings:
- [x] Add analytical expression to the code;
- [x] Add tests to integrate with pytest;
- [x] Add a working example from a book with results matching with ours (book must be referenced).

Long bearings:
- [ ] Add analytical expression to the code;
- [ ] Add a working example from a book with results matching with ours (book must be referenced);
- [ ] Add tests to integrate with pytest.

Middle size bearings:
- [x] Add numerical calculus to the code;
- [ ] Add the real data we have;
- [ ] Add tests to integrate with pytest (the real data and our results must match).

**Comment by JuliaMota** [comment]
I'm searching for examples that return the same information as our code. I've found some things that might be interesting in the book TRIBOLOGY SERIES, but these still need to be understood and adapted. 

Initially, we can include the density and viscosity of the ISO VG 32 and 46 oils to analyze the pressure behavior.

- Viscosity (Pa.s):
#visc= 0.032 # ISO VG 32 (40°C)
#visc= 0.0054 # ISO VG 32 (100°C)
#visc= 0.046 # ISO VG 46 (40°C)
#visc= 0.0068 # ISO VG 46 (100°C)

- Fluid density (Kg/m^3):
#rho = 857. # ISO VG 32
#rho = 861. # ISO VG 46

**Comment by JuliaMota** [comment]
The examples of viscosity and density quoted were included. But I have difficulty adapting the examples from the book to the code.In the book TRIBOLOGY SERIES, there is an example of an annular seal that is very close to our case. However, there seems to be a lack of necessary information. I keep researching and working on it.

**Comment by flaviorangel** [comment]
> The examples of viscosity and density quoted were included. But I have difficulty adapting the examples from the book to the code.In the book TRIBOLOGY SERIES, there is an example of an annular seal that is very close to our case. However, there seems to be a lack of necessary information. I keep researching and working on it.

This example doesn't seem to fit our case. Although it gives all entry data we need, except for grid information, its outputs are axial leakage rate of flow, friction torque, and dissipated power. Unless we can calculate those using our pressure matrix, it can't be adapted. It also infers the pressure as p = (1 - z/L), which are able to infer as well given a simple structure.

**Comment by JuliaMota** [comment]
Me and @flaviorangel  implemented an example from chapter 5 of the book "Tribology Series 33". The book presents the Sommerfeld solution for pressure calculation. We produced a graph that compares the analytical solution presented in the book with the results presented in our code. However, the results are different. See the graph: the red line represents the analytical result of the book while the blue line represents our result.
![Figure_5](https://user-images.githubusercontent.com/39375523/54381034-8b0f6e00-466b-11e9-9c87-dd4fe899231a.png)
Studying the text better, I have identified some possible errors:
1- The example shows a static case, so we should consider omega = 0
2- The book presents more than one static case. The case that we implemented is a long bearing (page 118), ie, according to the book L/D > 4 (L and D are width and diameter, respectively).

Note: An example of a short bearing is shown on page 127. I believe we can test it.

**Comment by flaviorangel** [comment]
Here what needs to be done to close this issue:

- [ ] Add analytical expression to the code in order to compare results;
- [ ] Add tests to integrate with pytest;
- [ ] Add a working example from a book with results matching with ours.

Anything else?

**Comment by flaviorangel** [comment]
We need to specify where our 'zero' is located in the circle. Some books suggest that it begins where 'h' is shorter, 'h' meaning the space between the rotor and the stator.

**Comment by raphaeltimbo** [comment]
I think this issue involves lots of different things. 
Maybe we could break it into different smaller issues (and consequently different PRs) to make it easier to track the work?

**Comment by flaviorangel** [comment]
> I think this issue involves lots of different things.
> Maybe we could break it into different smaller issues (and consequently different PRs) to make it easier to track the work?

Agreed. I'll break it in three and close this one.

**Comment by flaviorangel** [comment]
This issue was broken into issues #201 and #202. As for the short bearing, by the time it was broken, we were already being able to calculate its pressure.
