### ISSUE TITLE
Add CI for windows platform

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#40]
Add CI that uses windows. Verify if travis does this, if not, appveyor could be an option.

**Comment by GabrielBachmann** [comment]
The Travis CI does not support windows and linux enviroments. We'll have to use Appveyor as CI for windows testing.

**Comment by raphaeltimbo** [comment]
The repository settings have been modified to give authorization to appveyor.
Builds can be seen [here](https://ci.appveyor.com/project/raphaeltimbo/ross/builds/22998644).
