### ISSUE TITLE
ross-bott-tests

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#408]
I've created this issue just to run some tests with our bot.

**Comment by raphaeltimbo** [comment]
test create comment

**Comment by ross-bott** [comment]
testing

**Comment by ross-bott** [comment]
Hi there!I have marked this issue as stale because it has not had activity for 45 days.Consider the following options:- If the issue refers to a large task, break it in smaller issues that can be solved inless than 45 days;- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.Consider the following options:- If the issue refers to a large task, break it in smaller issues that can be solved inless than 45 days;- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
