### ISSUE TITLE
File save format

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#41]
instantiated rotors could be saved for future use. 

Saving elements (shaft, disk, bearing and seal) in different files. Each element class should have your own save file.

Other options are:

- saving the rotor assembly's matrices

- saving arrays from results to retrieve graphs.

- Autorun a method when the user opens a saved file showing the rotor model.

**Comment by GabrielBachmann** [comment]
The pull request #58 closes this issue.
