### ISSUE TITLE
Improving the tutorial - ShaftElement

### ISSUE THREAD

**Issue by rennergcm** [ross-rotordynamics/ross#416]
>How to create a shaft element with different outer diameter and length should be shown in this tutorial. We should keep in mind that the users are not expert in Python.
L = 0.25
i_d = 0
o_d = 0.05
N = 6       # Number of elements
l_list = [L for _ in range(N)]
shaft_elements = [
    rs.ShaftElement(
        L=l,
        i_d=i_d,
        o_d=o_d,
        material=Steel,
        shear_effects=True,
        rotary_inertia=True,
        gyroscopic=True,
    )
    for l in l_list
]

**Comment by rodrigomoliveira1** [comment]
@raphaeltimbo the tutorial for ShaftElement class does not match the version 0.2.0 build.
The 0.2.0 build does still have the ShaftTaperedElement class.

We should add an example building a tapered element to teach the users how to instantiate it and change the docstring (from ShaftElement) shown in the tutorial. It belongs to the current ShaftElement class (not in the 0.2.0).
