### ISSUE TITLE
Improving the Tutorial - From section instantiation of a Rotor

### ISSUE THREAD

**Issue by rennergcm** [ross-rotordynamics/ross#418]
**It is hard to understand the explanation below, although it easier to create the rotor using this method(i_ds_data = [0,0,0]
o_ds_data = [0.05, 0.05, 0.05]
leng_data = [0.5, 0.5, 0.5]**.

n this form of instantiation, the number of shaft elements used in FEM are not fixed, instead, the program does a convergence analysis, testing the number of elements to a point where the relative error between iterations reaches a value that can be neglected.
To use this method, you should divide the rotor in a way where the number of shaft elements is minimal and place every element (except for the shaft elements) in the minimal nodes

**Comment by raphaeltimbo** [comment]
@rodrigomoliveira1 , when we use the `.from_section()` method is the rotor automatically subdivided in several elements?

**Comment by rodrigomoliveira1** [comment]
> @rodrigomoliveira1 , when we use the .from_section() method is the rotor automatically subdivided in several elements?

Yes, and the user chooses how many elements it should be inserted in each shaft section
