### ISSUE TITLE
Improving the Tutorial - Running the simulation

### ISSUE THREAD

**Issue by rennergcm** [ross-rotordynamics/ross#420]
#How to run a model with others rotor speed. An example should be shown. We should keep in mind that the users might not be expert in Python.

rotor_speed =150
modal = rotor1.run_modal(rotor_speed)
modal.wn

**Comment by raphaeltimbo** [comment]
This is now at the tutorial:
```python
rotor_speed1 = 200.0
modal = rotor1.run_modal(rotor_speed1)

rotor_speed2 = 100.0
modal = rotor1.run_modal(rotor_speed2)
```
