### ISSUE TITLE
Improving the Tutorial - Static analysis

### ISSUE THREAD

**Issue by rennergcm** [ross-rotordynamics/ross#421]
**a. Units should be added in axis name
b. What does 'w' mean in Free-Body Diagram? Weight of the shaft? If yes, representing weight/length_unit is more suitable**

show(static.plot_deformation())
show(static.plot_free_body_diagram())
show(static.plot_shearing_force())
show(static.plot_bending_moment())

**Comment by raphaeltimbo** [comment]
This will be solved in #440 .
