### ISSUE TITLE
Improving the Tutorial - Frequency Response

### ISSUE THREAD

**Issue by rennergcm** [ross-rotordynamics/ross#423]
**Instead of using Frenquency response, I suggest to use Bode Plot. What is the aim of this plot? Maybe is it not necessary. It is difficult to understand the meaning of Input and Output. For instance, Input=zero means node position or a direction of a vector.** 

response = rotor1.run_freq_response(np.linspace(0, 200, 101))
show(response.plot(inp=0,out=0,plot_type='bokeh'))

**Comment by raphaeltimbo** [comment]
We've added the following explanation to the notebook


### Frenquency Response

```text
    speed_range : array, optional
        Array with the desired range of frequencies (the default
         is 0 to 1.5 x highest damped natural frequency.
    modes : list, optional
        Modes that will be used to calculate the frequency response
        (all modes will be used if a list is not given).
```

We can put the frequency response of selecting the input and output degree of freedom.
- Input is the degree of freedom to be excited;
- Output is the degree of freedom to be observed.

Each shaft node has 4 local degrees of freedom (dof) $[x, y, \alpha, \beta]$, and each degree of freedom has it own index:
- $x$ -> index 0
- $y$ -> index 1
- $\alpha$ -> index 2
- $\beta$ -> index 3

Taking the rotor built as example, let's excite the node 3 (in the $y$ direction) and observe the response on the node 2 (also in $y$ direction):

$global\_dof = dof\_per\_node * node\_number + dof\_index$

node 2, local dof $y$:

$out = 4 * 2 + 1 = 9$

node 3, local dof $y$:

$inp = 4 * 3 + 1 = 13$

To run the Frequency Response, use the command `.run_freq_response()`

To plot the figure, use the command `run_freq_response().plot()`
