### ISSUE TITLE
Improving the tutorial - Unbalance Response

### ISSUE THREAD

**Issue by rennergcm** [ross-rotordynamics/ross#424]
**a. Adding an example of multiple unbalances instantiating node
b. dof=13 means what? Which node  is the response given?**

node = 3
magnitude = 0.03
phase = 0
frequency_range=np.linspace(0, 200, 101)

unbalance = rotor1.unbalance_response(node, magnitude, phase, frequency_range)
show(unbalance.plot(dof=13, plot_type="bokeh"))

**Comment by raphaeltimbo** [comment]
The following explanation has been added to the tutorial:
### Unbalance Response

This method returns the unbalanced response for a mdof system given magnitide and phase of the unbalance, the node where it's applied and a frequency range.

```text
    node : list, int
        Node where the unbalance is applied.
    magnitude : list, float
        Unbalance magnitude (kg.m)
    phase : list, float
        Unbalance phase (rad)
    frequency_range : list, float
        Array with the desired range of frequencies
```
To run the Unbalance Response, use the command `.unbalance_response()`

To plot the figure, use the command `.unbalance_response().plot()`

Where `dof` is the degree of freedom for which you want to plot the response, which follows the same logic applied to Frequency Response.

In this following example, we can obtain the response for a given unbalance (kg.m) and its respective phase in a selected node. Notice that it's possible to add multiple unbalances instantiating node, magnitude and phase as lists.

```text
Unbalance1: node = 4
            magnitude = 0.03
            phase = 0
Unbalance2: node = 2
            magnitude = 0.02
            phase = 3.1415
```
