### ISSUE TITLE
Improving the Tutorial - Calculate Orbits

### ISSUE THREAD

**Issue by rennergcm** [ross-rotordynamics/ross#425]
**a. The size of the label should be optimize.
b. How to plot the graph in 2D?**

speed = 150.0
size = 1000
node = 3
t = np.linspace(0, 10, size)
F = np.zeros((size, rotor1.ndof))
F[:, 4 * node] = 10 * np.cos(2 * t)
F[:, 4 * node + 1] = 10 * np.sin(2 * t)
response = rotor1.run_orbit_response(speed, F, t)

response.plot(plot_type="3d")

**Comment by raphaeltimbo** [comment]
Rodrigo added an explanation to plot in 2d.
