### ISSUE TITLE
Improving Tutorial - Mode Shapes

### ISSUE THREAD

**Issue by rennergcm** [ross-rotordynamics/ross#426]
a. How to plot this graph in 2D? I do not think mode shape in 3D useful.

speed = 10
modes = rotor1.run_modal(speed)
modes.plot_mode(0)

**Comment by rodrigomoliveira1** [comment]
I did a 2D mode shape graph for api_report.py. 
I could copy / move the code to results.py for a plot2D method

**Comment by raphaeltimbo** [comment]
> 
> 
> I did a 2D mode shape graph for api_report.py.
> I could copy / move the code to results.py for a plot2D method

That would be good.

**Comment by rodrigomoliveira1** [comment]
Is it ok this way? Or should I add some marks to indicate the bearings locations.
I'm plotting with matplotlib. For each whirl direction, there's a different color:

- Forward: blue
- Mixed: black
- Backward: red

![Figure_4](https://user-images.githubusercontent.com/45969994/74853465-b9d2a180-531c-11ea-8c2b-cca3e681f53e.png)
![Figure_3](https://user-images.githubusercontent.com/45969994/74853468-bb03ce80-531c-11ea-8ec7-196170895a42.png)
