### ISSUE TITLE
ShaftElement 6 gdl code

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#430]
I am opening this issue to organize the implementation for a shaft element with 6 dof.

- [ ] Implement mass matrix without rotary inertia;
- [ ] Implement mass matrix with rotary inertia;
- [ ] Implement stiffness matrix.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
#502 implemented this.
