### ISSUE TITLE
Add damping coefficients to fluid flow

### ISSUE THREAD

**Issue by JuliaMota** [ross-rotordynamics/ross#435]
This issue came from issue #261 , being divided into a smaller problem. In order to close it, we need to add the numerical damping coefficients and to implement a test showing that the results match the expected.

To calculate the damping coefficients, the authors suggest a small perturbation in the journal center velocities to do so. However, we are not sure how to implement this perturbation. Because our rotor works in steady state, these velocities are zero (it's not moving). Some attempts were made on how to calculate the damping matrix and compared it with Friswell's non-numerical way:

- Attempt 1- Changing angular frequency;
- Attempt 2- Changing angular frequency, but replacing the rotor velocity with the fluid velocity;
- Attempt 3- Changing angular frequency, keeping the rotor in same position, replacing the rotor velocity with the fluid velocity.

The results of these attempts are recorded in the old issue #261  and none have been successful.

We continue to study the references on the subject. I think that to find the damping matrices it is necessary to consider the time variable in the equations. A more practical idea is to initially try to implement a model already ready and well accepted in the literature, without deducting the equations from the beginning.

**Comment by JuliaMota** [comment]
When studying the means of returning with the temporal variation in the model, I realized that the only elements that vary with time are the eccentricity `eccentricity = eccentricity(t)`  and the attitude angle `attitude_angle = attitude_angle(t)`.

I think that this way, we just need to find out how the center of the rotor moves over time. It would be enough to apply a step in time after the position of stability (which we already know) in these two functions and apply the new values in the model already known.

**Comment by JuliaMota** [comment]
New tests performed for the data:

nz = 16
ntheta = 132
nradius = 8
omega = 100.0 * 2 * np.pi / 60
p_in = 0.0
p_out = 0.0
radius_rotor = 0.1999996
radius_stator = 0.1999996 + 0.000194564
length = (1 / 10) * (2 * radius_stator)
load = 525
visc = 0.015
rho = 860.0

the equilibrium position is calculated by the program.

In order to verify the temporal variation of the eccentricity using the suggestion of the last meetings, it was adopted

```
e[0] = difference_between_radius * cos(omega * 0 * dtime)
for i in range(1, t):
    e[i] = e[i-1] * cos(omega * t * dtime)
```
The attitude angle was calculated using the function calculate_attitude_angle (eccentricity_ratio), where eccentricity_ratio was calculated for each new eccentricity.

Using dtime = 0.0001 with t = 300, I got the following behavior:

![Figure_1](https://user-images.githubusercontent.com/39375523/76772267-5f8ff980-677f-11ea-9014-fbfd9830556a.png)

This movement, compared to lightning, is almost imperceptible.

![Figure_2](https://user-images.githubusercontent.com/39375523/76772321-70d90600-677f-11ea-8b06-9fa6348b99d6.png)

I am carrying out some tests using this temporal movement to disturb the center of the rotor and achieve the damping coefficients.
The derivatives of the eccentricity and the attitude angle in relation to time are:

```
delta_e_dot = - e0 * omega * sin(omega * dtime)
delta_beta_dot = (4 * (pi)**0.5 * omega * sin(omega * dtime))/((1 - (cos(omega * dtime))**2)**0.5 *((pi - 16) * (cos(omega * dtime))**2 - pi))
```
where e0 is the eccentricity in the equilibrium position.

Thus, making the projections, the center of the rotor will be disturbed in the x direction with:

`delta_x_dot = sin(beta0 + delta_beta_dot) * (delta_e_dot)`

and in the y direction with:

`delta_y_dot = cos(beta0 + delta_beta_dot) * (delta_e_dot)`

That done I found the following results:

Coefficients: Cxx, Cxy, Cyx, Cyy
Friswel Reference: 66379.3691125331 -443009.0015472785 -443009.0015472785 6497074.271829649
Numerical result: -105253150.4669472 718262212.5983746 -422459.5455815739 4076943.608019093
Relative errors: 1586.6304733555285 1622.326451809627 0.046386091239528714 0.37249545911825016

I was under the impression that the results referring to the y components of the forces showed a better error. Does anyone have any suggestions or is this just a coincidence?

**Comment by JuliaMota** [comment]
There was an error in calculating the variation of the eccentricity over time. The correct form is:
```
e[0] = difference_between_radius * cos(omega * 0 * dtime)
for i in range(1, t):
    e[i] = e[i-1] * cos(omega * i * dtime)
```
![variacao-excentricidade-tempo](https://user-images.githubusercontent.com/39375523/77343645-c6c62480-6d10-11ea-900c-2c5e96117774.png)

**Comment by JuliaMota** [comment]
I organized the code in a more structured way and managed to find the step in the closest time to the equilibrium position calculated by the program.
The implementation follows the following steps:

**STEP 1:** calculate the values in the equilibrium position

- eccentricity -> e0
- attitude_angle -> beta0
- forces - radial_force, tangential_force, force_x, force_y
- xi, yi (rotor center) -> xi0, yi0
- reference damping coefficients -> cxx, cxy, cyx, cyy

**STEP 2:** find out what time is the equilibrium position

I consider a step in time dtime = 0.0001.

For the eccentricity I use e_ (t + 1) = e_t * cos (omega * t), where t = i * dtime, where i is the iteration index.
When t = 0, e_1 = c * cos (omega * 0), where c = R_o - R_i.

Each new eccentricity generates a new eccentricity ratio and, consequently, a new attitude angle.

Information about the rotor position at each step in time is stored in an array. From then on it is possible to find out which point is closest to the equilibrium position and at what point in time this occurs.

**STEP 3:** calculate the rotor position in the next time step

Knowing that the equilibrium position is at time t, I consider time t + 1.
```
e0_1 = e [t + 1]
beta0_1 = beta [t + 1]
xi0_1 = xi [t + 1]
yi0_1 = yi [t + 1]
```

**STEP 4:** find how much x and y vary over time
```
delta_x = xi0_1 - xi0
delta_y = yi0_1 - yi0
```
**STEP 5:** disturb the center of the rotor by adding delta_x and calculate the new forces

```
fluid_flow_object.xi = fluid_flow_object.xi + delta_x
fluid_flow_object.yi = fluid_flow_object.yi
fluid_flow_object.eccentricity = np.sqrt (fluid_flow_object.xi ** 2 + fluid_flow_object.yi ** 2)
fluid_flow_object.eccentricity_ratio = fluid_flow_object.eccentricity / fluid_flow_object.difference_between_radius
fluid_flow_object.attitude_angle = np.arctan (fluid_flow_object.xi / fluid_flow_object.yi)
fluid_flow_object.calculate_coefficients ()
fluid_flow_object.calculate_pressure_matrix_numerical ()
```
radial_force_x, tangential_force_x, force_x_x, force_y_x

**STEP 6:** I return to the equilibrium position, disturb the center of the rotor by adding delta_y and calculate the new forces

```
fluid_flow_object.xi = fluid_flow_object.xi - delta_x
fluid_flow_object.yi = fluid_flow_object.yi + delta_y
fluid_flow_object.eccentricity = np.sqrt (fluid_flow_object.xi ** 2 + fluid_flow_object.yi ** 2)
fluid_flow_object.eccentricity_ratio = fluid_flow_object.eccentricity / fluid_flow_object.difference_between_radius
fluid_flow_object.attitude_angle = np.arctan (fluid_flow_object.xi / fluid_flow_object.yi)
fluid_flow_object.calculate_coefficients ()
fluid_flow_object.calculate_pressure_matrix_numerical ()
```
radial_force_y, tangential_force_y, force_x_y, force_y_y

**STEP 7:** I return to the equilibrium position

```
fluid_flow_object.xi = fluid_flow_object.xi
fluid_flow_object.yi = fluid_flow_object.yi - delta_y
fluid_flow_object.eccentricity = np.sqrt (fluid_flow_object.xi ** 2 + fluid_flow_object.yi ** 2)
fluid_flow_object.eccentricity_ratio = fluid_flow_object.eccentricity / fluid_flow_object.difference_between_radius
fluid_flow_object.attitude_angle = np.arctan (fluid_flow_object.xi / fluid_flow_object.yi)
fluid_flow_object.calculate_coefficients ()
fluid_flow_object.calculate_pressure_matrix_numerical ()
```
**STEP 8:** calculate the coefficients

```
c_xx = (force_x - force_x_x) / delta_x_dot
c_yx = (force_y - force_y_x) / delta_x_dot
c_xy = (force_x - force_x_y) / delta_y_dot
c_yy = (force_y - force_y_y) / delta_y_dot

```
In this last step, it is necessary to investigate what will be used as delta_x_dot and delta_y_dot.
Using the same input data presented earlier, I arrive at the results:

Balance position: (2.8320358353730492e-05, -0.0001890071244346679)
Next step in time: (2.891841365302544e-05, -0.00018881915295644027)
Adding delta_x: (2.891841365302544e-05, -0.0001890071244346679)
Adding delta_y: (2.8320358353730492e-05, -0.00018881915295644027)

![Rotor_center_position](https://user-images.githubusercontent.com/39375523/77768257-f92d9580-7020-11ea-8023-db88c64dc818.png)

Zooming in for a better view:

![Disturbance](https://user-images.githubusercontent.com/39375523/77768279-021e6700-7021-11ea-9a38-ac22b7de39f0.png)

**Results:**

**1)** delta_x_point = delta_x and delta_y_point = delta_y

Damping coefficients: cxx, cxy, cyx, cyy
Reference: 66379.3691125331, -443009.0015472785, -443009.0015472785, 6497074.271829649
Numeric: -17967067268.073578, -49598124697.73019, -1335599645.5619566, 23306762364.092716
Relative error: 270673.46206594654, 111956.37451045227, 3013.836359751529, 3586.270421880104

**2)** Considering how the speed: delta_x_point = delta_x / dtempo and delta_y_point = delta_y / dtempo

Damping coefficients: cxx, cxy, cyx, cyy
Reference: 66379.3691125331, -443009.0015472785, -443009.0015472785, 6497074.271829649
Numeric: -1796706.726807358, -4959812.469773019, -133559.9645561957, 2330676.2364092716
Relative error: 28.067246206594657, 10.195737451045227, 0.6985163640248471, 0.6412729578119896

The relative errors are calculated as follows:

```
error_xx = np.abs((c_xx-cxx)/cxx)
error_xy = np.abs((c_xy-cxy)/cxy)
error_yx = np.abs((c_yx-cyx)/cyx)
error_yy = np.abs((c_yy-cyy)/cyy)
```

**Comment by JuliaMota** [comment]
I did other tests adopting another reference. Steps 1, 2, 3 and 4 have the same theory. Only the nomenclatures of these steps are noted here.

**STEP 1:** calculate the values ​​in the equilibrium position
- eccentricity -> e0
- attitude_angle -> beta0
- eccentricity_ratio -> epsilon0
- forces - radial_force_0, tangential_force_0, force_x_0, force_y_0
- xi, yi (rotor center) -> xi0, yi0
- reference damping coefficients -> cxx, cxy, cyx, cyy

**STEP 2:** find out what time is the equilibrium position

**STEP 3:** calculate the rotor position in the next time step
```
e0_1 = e [t + 1]
beta0_1 = beta [t + 1]
epsilon0_1 = e0_1 / fluid_flow_object.difference_between_radius
xi0_1 = xi [t + 1]
yi0_1 = yi [t + 1]
```
**STEP 4:** find the variations in time
```
delta_e = e0_1 - e0
delta_beta = beta0_1 - beta0
delta_epsilon = epsilon0_1 - epsilon0
delta_x = xi0_1 - xi0
delta_y = yi0_1 - yi0
```
**STEP 5:** disturb the center of the rotor for the next step in time
```
fluid_flow_object.eccentricity = e0_1
fluid_flow_object.attitude_angle = beta0_1
fluid_flow_object.eccentricity_ratio = epsilon0_1
fluid_flow_object.xi = fluid_flow_object.eccentricity * np.cos (3 * np.pi / 2 + fluid_flow_object.attitude_angle)
fluid_flow_object.yi = fluid_flow_object.eccentricity * np.sin (3 * np.pi / 2 + fluid_flow_object.attitude_angle)
```

**STEP 6:** Calculate the new forces
```
fluid_flow_object.calculate_coefficients ()
fluid_flow_object.calculate_pressure_matrix_numerical ()
[radial_force_1, tangential_force_1, force_x_1, force_y_1] = \
            calculate_oil_film_force (fluid_flow_object, force_type = 'numerical')
```
**STEP 7:** I return to the equilibrium position
```
fluid_flow_object.eccentricity = e0
fluid_flow_object.attitude_angle = beta0
fluid_flow_object.eccentricity_ratio = epsilon0
fluid_flow_object.xi = fluid_flow_object.eccentricity * np.cos (3 * np.pi / 2 + fluid_flow_object.attitude_angle)
fluid_flow_object.yi = fluid_flow_object.eccentricity * np.sin (3 * np.pi / 2 + fluid_flow_object.attitude_angle)
```
**STEP 8:** calculate the coefficients in the radial and tangential directions (according to Pedreira, 2006)
```
delta_x_point = delta_x / dtempo
delta_y_point = delta_y / dtempo
delta_e_point = delta_e / dtempo
delta_beta_ponto = delta_beta / dtempo
delta_epsilon_ponto = delta_epsilon / dtempo

c_rr = - (radial_force_0 - radial_force_1) / (fluid_flow_object.difference_between_radius * delta_epsilon_point)
c_rt = - (radial_force_0 - radial_force_1) / (fluid_flow_object.difference_between_radius
                                            * epsilon0 * delta_beta_point)
c_tr = - (tangential_force_0 - tangential_force_1) / (fluid_flow_object.difference_between_radius * delta_epsilon_point)
c_tt = - (tangential_force_0 - tangential_force_1) / (fluid_flow_object.difference_between_radius
                                                      * epsilon0 * delta_beta_point)
```
**STEP 9:** rotation to the damping coefficients (according to Pedreira, 2006)
```
a = c_rr * np.sin (beta0) + c_rt * np.cos (beta0)
b = c_tr * np.sin (beta0) + c_tt * np.cos (beta0)
c = - c_rr * np.cos (beta0) + c_rt * np.sin (beta0)
d = - c_tr * np.cos (beta0) + c_tt * np.sin (beta0)

c_xx = np.sin (beta0) * a + np.cos (beta0) * b
c_xy = (np.sin (beta0) * c + np.cos (beta0) * d)
c_yx = - np.cos (beta0) * a + np.sin (beta0) * b
c_yy = (- np.cos (beta0) * c + np.sin (beta0) * d)
```

**Results**

Equilibrium position (x, y, e, beta): (2.8320358353730492e-05, -0.0001890071244346679, 0.000191117073502986, 0.14873103693243736)
Next step in time (x, y, e, beta): (2.8700491138791125e-05, -0.0001888523999841867, 0.0001910208029807096, 0.15081910246872093)

![Disturbance](https://user-images.githubusercontent.com/39375523/77826836-b4712f80-70f0-11ea-9075-b98fe30db317.png)

Damping coefficients: crr, crt, ctr, ctt
Numeric: 1512375.1859406366 -364845.7226364294 168998.19313215333 -40769.16129723616
Damping coefficients: cxx, cxy, cyx, cyy
Reference: 66379.3691125331 -443009.0015472785 -443009.0015472785 6497074.271829649
Numeric: -35365.702268622714 -400907.8458709767 132936.069897606 1506971.726912023
Relative error 1.5327815365142619 0.09503453773909086 1.300075324504256 0.7680537940829723


We can force cxy = cyx as in the references, however the ideal would be for this to happen naturally.
Some signs are exchanged too. Could it be an error in the rotation?
For the first time, the reference values ​​and those calculated numerically have the same order of magnitude.

Pedreira, Javã Atayde; Weber, Hans Ingo. Dinâmica de Máquinas Rotativas em Mancais Hidrodinâmicos. Rio de Janeiro, 2006. 113p. Dissertação de Mestrado — Departamento de Engenharia Mecânica, Pontifícia Universidade Católica do Rio de Janeiro.

**Comment by JuliaMota** [comment]
Correcting the function that determines the behavior of the eccentricity over time to:
```
    for i in range(t):
        e[i] = fluid_flow_object.difference_between_radius * np.cos(omega * i * dtime)
```
Remembering that the attitude angle is calculated from the eccentricity, it varies with time as a consequence. I find the following path from the center of the rotor:

![variacao-excentricidade-tempo2](https://user-images.githubusercontent.com/39375523/78503833-7a7ed980-773f-11ea-9ff1-fe1cc32181c9.png)

This result seems more appropriate, because after a certain moment, the position of the center of the rotor stops varying with time and does not become concentric as in the previous way.

Another change was made to calculate the time derivatives of eccentricity, eccentricity ratio and attitude angle. Previously they were being calculated by the difference between the values ​​in the equilibrium position and after the disturbance. They are now calculated based on the result of the partial time derivative itself.

We then have:

```
delta_e_point = - fluid_flow_object.difference_between_radius * omega * np.sin((t) * dtime * omega)

delta_epsilon_point = delta_e_point / fluid_flow_object.difference_between_radius

delta_beta_point = (((np.pi * (1 - (e0**2 / fluid_flow_object.difference_between_radius**2) * delta_e_point)**0.5) / (4 * fluid_flow_object.difference_between_radius)) - ((np.pi * e0**2 * delta_e_point) / (4 * fluid_flow_object.difference_between_radius**3 * (1 - e0**2 / fluid_flow_object.difference_between_radius**2)**0.5))) / ((np.pi * e0**2 * (1 - e0**2 / fluid_flow_object.difference_between_radius**2)) / (16 * fluid_flow_object.difference_between_radius**2) + 1)
```
Following the same steps used in the previous test, we obtain:

Damping coefficients: cxx, cxy, cyx, cyy
Reference: 66379.3691125331, -443009.0015472785, -443009.0015472785, 6497074.271829649
Numeric: 14594.120726225956, -97731.12527053713, -10327.14926148023, 69156.88427515568
Relative error 0.7801407135779717, 0.7793924617125255, 0.976688624327246, 0.9893556882095361

The result is still very bad and the values differ considerably from what they should be. However, in this way, all signals are correct.

**Comment by JuliaMota** [comment]
Trying to find the reason why the absolute values ​​of the coefficients are wrong, I used the forces found from the approximation for a short bearing, presented by Ishida and Yamamoto (2012), to calculate the coefficients.

Before the disturbance, the relative error of the radial and tangential forces were approximately 18% and 19%, respectively. After the disturbance, these errors became 17% and 18%.

Despite being a relatively high error, it was considered acceptable so far. However, exchanging the numerical forces for the approach of the short bearing, we obtain the following results for the damping coefficients:

Damping coefficients: cxx, cxy, cyx, cyy
Reference: 66379.3691125331, -443009.0015472785, -443009.0015472785, 6497074.271829649
Numeric: 89975.86516861686, -602544.4507362476, -337844.4776626828, 2262454.6576578915
Relative error 0.3554793661277583, 0.36011785004766605, 0.23738687818372098, 0.6517733116477428

Note that the errors are still high (mainly in cyy), but have decreased considerably. This may indicate an error in the way of calculating the forces numerically or else that the errors, accumulated during the code, impact the damping coefficients more strongly.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
