### ISSUE TITLE
Change _calc_system() to run()

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#44]
Currently, the calculation of some rotor parameters such as eigenvalues, damping rations etc. is done automatically when the speed (w) is changed. This calculation not carried out in an explicit manner, meaning that the user is not aware that these parameters are being recalculated when the speed is modified.
Maybe a better approach would be to implement a run() method that would have to be explicitly called by the user to update the rotor state.

**Comment by GabrielBachmann** [comment]
The pull request #58 closes this issue.
