### ISSUE TITLE
fluid_flow tests are taking too long to run

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#442]
The tests on fluid flow are taking a long time to run. Can we simplify the tests so they can faster?
@JuliaMota Can you look at this?

**Comment by JuliaMota** [comment]
Ok!  I will work on it.

**Comment by JuliaMota** [comment]
The changes made by pull request #446 reduced the test time from 7m to 3m, approximately. The longest delay occurs in the function 'test_find_equilibrium_position' because it is an iterative method. 
Is the time spent good for testing or is it necessary to reduce more?

**Comment by raphaeltimbo** [comment]
Is it possible to reduce the `test_find_equilibrium_position` by reducing the number of iterations (or maybe reducing the tolerance)? If you could reduce more time in this test it would be great, but if it is not possible I think the reduction you've already achieved is good enough and we can merge the PR.

**Comment by JuliaMota** [comment]
I made another modification reducing the number of iterations of the function `test_find_equilibrium_position`.
Initially the fluid-flow tests took 7m 20s. After the initial modifications this time was reduced to 32s. Now, on my computer, it's taking about 15s.

Is this a good time? If the answer is affirmative, this issue can be closed after merging the PR.

**Comment by raphaeltimbo** [comment]
> 
> 
> I made another modification reducing the number of iterations of the function `test_find_equilibrium_position`.
> Initially the fluid-flow tests took 7m 20s. After the initial modifications this time was reduced to 32s. Now, on my computer, it's taking about 15s.
> 
> Is this a good time? If the answer is affirmative, this issue can be closed after merging the PR.

Yes. This is good. I've already merged #446 
Thanks!
