### ISSUE TITLE
Static Analysis for Co-Axial Rotors

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#443]
Issue to discuss how to return the results and plot from static analysis considering the `CoAxialRotor` class (Issue #276).

Right now I'm thinking about 2 options to plot the results for Static Analysis (`StaticResults` and `.run_static()`), which can be extrapolated for the other methods:

1. Plotting separated graphs for each shaft (see below how it looks):

![image](https://user-images.githubusercontent.com/45969994/74457278-ccedf900-4e66-11ea-9e1a-77eeb9f62153.png)
 

2. Plotting all the curves in the same plot (see below): 

![image](https://user-images.githubusercontent.com/45969994/74459683-839fa880-4e6a-11ea-9763-3aeaaa3ba989.png)

**Comment by raphaeltimbo** [comment]
I would go with the option two for the coaxial object.
If the user wants a separated plot for each rotor he should be able to get that by accessing each rotor. Something like:
```python
results = coaxial_rotor.rotors[0].run_static()
```
