### ISSUE TITLE
Listing functions to adapt to CoAxialRotor class

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#454]
This issue is to track the methods that requires changes to adapt to CoAxialRotor class.
- [ ] `run_modal()`
- [ ] `convergence()`
- [ ] `run_freq_response()`
- [ ] `unbalance_response()`
- [ ] `run_campbell()`
- [ ] `run_time_response()`
- [ ] `run_orbit_response()`
- [x] `run_static()`
- [ ] `plot_level1()`
- [ ] `plot_ucs()`

Maybe, some of these methods won't require any change, and the other submethods will. If it's the case, this will be documented here.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
@rodrigomoliveira1 , since you labeled this one as `wontfix for now` I am closing it and we can reopen it later.
