### ISSUE TITLE
Add Statement of Need

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#460]
Please add a Statement of Need to your README/documentation. It's preferable that this is one of the first things a reader would see in the README.

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
Hi there @nnadeau ! Thank you for your comments. 
We have just released v0.3.0 and I have updated de README file to give a better explanation on the use of our software. Let us know if that is ok to you.

**Comment by nnadeau** [comment]
:+1:
