### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by srmnitc** [ross-rotordynamics/ross#471]
This is part of my review of the software paper at openjournals/joss-reviews#2120

I tried the installation as mentioned in the documentation in a clean environment with python 3.8.
Upon import the module as,
```
import ross as rs
```
the error I get is,
```
  File "~/anaconda3/envs/testross/lib/python3.8/site-packages/pint/registry.py", line 532, in load_definitions
    raise ValueError("While opening {}\n{}".format(file, msg))
ValueError: While opening ~/anaconda3/envs/testross/lib/python3.8/site-packages/ross/new_units.txt
[Errno 2] No such file or directory: '~/anaconda3/envs/testross/lib/python3.8/site-packages/ross/new_units.txt'
```

**Comment by srmnitc** [comment]
I can confirm that installing from the repo using `pip install git+https://github.com/ross-rotordynamics/ross.git` works fine. Maybe the pypi version is not updated?

**Comment by raphaeltimbo** [comment]
Hi there @srmnitc ! We have updated the `MANIFEST.in` file to add the missing file to the pypi package. I have tested and it looks like we solved the problem. Feel free to reopen the issue if you have any problems!
