### ISSUE TITLE
Binder information could be added to docs

### ISSUE THREAD

**Issue by srmnitc** [ross-rotordynamics/ross#473]
The binder link can be added to examples/tutorials section of the docs. The binder link is quite useful as an introduction.

Also, it would be great if the notebooks are named numerically, so as to give the user an idea about how to progress in the examples.

These are not blocking acceptance of the journal, just my suggestions. Fell free to ignore/implement them.

**Comment by raphaeltimbo** [comment]
Hi there @srmnitc !
We have added this line to the docs webpage:
![image](https://user-images.githubusercontent.com/18506378/78393940-1c2bec80-75c1-11ea-9ab5-28cb6e0853dd.png)
I have also renamed the examples:
![image](https://user-images.githubusercontent.com/18506378/78393997-349c0700-75c1-11ea-8529-f463c959e02f.png)
