### ISSUE TITLE
Validating input values

### ISSUE THREAD

**Issue by srmnitc** [ross-rotordynamics/ross#474]
Input values are validated at some places, but not everywhere. For example, for something as important as the `Material` class, it would be good to check the values `rho`, `E`, `G_s` etc for the type and raise a `TypeError` if required.

Once again, I do not find this blocking of acceptance of the paper, so feel free to implement or ignore.

**Comment by raphaeltimbo** [comment]
Have changed the code so that these arguments will be floats:
![image](https://user-images.githubusercontent.com/18506378/78405421-d67a1e80-75d6-11ea-8931-17e46679533b.png)
