### ISSUE TITLE
Missing DOI

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#480]
https://github.com/ross-rotordynamics/ross/blob/4de0c5bf825a241859fb989bb28ada128157a9e0/paper/paper.bib#L27-L32

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
Unfortunately, we could not find the doi for this reference.

**Comment by nnadeau** [comment]
@raphaeltimbo the recommended citation is found here: https://www.scipy.org/citing.html

**Comment by raphaeltimbo** [comment]
Thank you @nnadeau !
I've added the recommended citation on ac9c755.

**Comment by nnadeau** [comment]
fixed in https://github.com/ross-rotordynamics/ross/commit/ac9c7557b5c3d8fcb1530bbf1e9fa23202c1ade0
