### ISSUE TITLE
Missing DOI

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#481]
https://github.com/ross-rotordynamics/ross/blob/4de0c5bf825a241859fb989bb28ada128157a9e0/paper/paper.bib#L34-L39

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
We could not find a doi for this reference. We have copied the citation information from bokeh’s website (https://bokeh.org/citation/) 

 
![image](https://user-images.githubusercontent.com/18506378/78302806-f1368f80-7511-11ea-8001-d5b29816b73e.png)

**Comment by nnadeau** [comment]
:+1:
