### ISSUE TITLE
In-text citations should be in chronological order

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#483]
e.g., 

https://github.com/ross-rotordynamics/ross/blob/master/paper/paper.md#L50

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
Based on #484, we have kept only the Friswell, Penny, Garvey & Lees, 2010 reference, so this should not be a problem anymore.

**Comment by nnadeau** [comment]
fixed in https://github.com/ross-rotordynamics/ross/pull/504
