### ISSUE TITLE
MATLAB is uppercase

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#485]
https://github.com/ross-rotordynamics/ross/blob/master/paper/paper.md#L55

MATLAB is uppercase

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
This has been fixed on commit 16a0394.

**Comment by nnadeau** [comment]
fixed in https://github.com/ross-rotordynamics/ross/pull/504
