### ISSUE TITLE
`independent` software?

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#486]
https://github.com/ross-rotordynamics/ross/blob/master/paper/paper.md#L54-L58

what is `independent` software?

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
The purpose of the ‘independent’ here was to say that these softwares do not depend on other softwares such as COMSOL, ANSYS or MATLAB. 

We have modified the text: 
![image](https://user-images.githubusercontent.com/18506378/78303011-44a8dd80-7512-11ea-9947-ee1f2566416c.png)

**Comment by nnadeau** [comment]
fixed in https://github.com/ross-rotordynamics/ross/pull/504
