### ISSUE TITLE
`Timoshenko beam theory`

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#487]
https://github.com/ross-rotordynamics/ross/blob/master/paper/paper.md#L60-L63

no citation for `Timoshenko beam theory` ?

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
We have added the Hutchinson (2001) reference, which explains the Timoshenko beam theory.

**Comment by nnadeau** [comment]
fixed in https://github.com/ross-rotordynamics/ross/pull/504
