### ISSUE TITLE
Improve explanation of simulation/modeling assumptions

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#488]
https://github.com/ross-rotordynamics/ross/blob/master/paper/paper.md#L62-L63

`Disks are assumed to be rigid bodies, thus their strain energy is not taken 
into account. And bearings/seals are included as linear stiffness/damping coefficients.`

Why? Does this differ from other approaches?

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
We have added more explanation to the modeling assumptions:

**Comment by nnadeau** [comment]
fixed in https://github.com/ross-rotordynamics/ross/pull/510
