### ISSUE TITLE
Oxford commas

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#489]
Use Oxford commas and break into smaller phrases/sentences for easier reading: 

https://github.com/ross-rotordynamics/ross/blob/master/paper/paper.md#L79-L82

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
We have tried to improve this on commit 17c399c.

**Comment by nnadeau** [comment]
fixed in https://github.com/ross-rotordynamics/ross/pull/504
