### ISSUE TITLE
Better Python packages explanation

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#490]
https://github.com/ross-rotordynamics/ross/blob/master/paper/paper.md#L84-L85

Why? 

cc cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
We have added a short explanation on why we are using each package.

**Comment by nnadeau** [comment]
Fixed in https://github.com/ross-rotordynamics/ross/pull/504
