### ISSUE TITLE
`software is extensible` claim

### ISSUE THREAD

**Issue by nnadeau** [ross-rotordynamics/ross#492]
`The software is extensible and new elements or new types of analysis can be easily included.` 

What kind of extensibility? Any examples?

cc https://github.com/openjournals/joss-reviews/issues/2120

**Comment by raphaeltimbo** [comment]
We have added the following to the text: 

_"ROSS is extensible and new elements, such as different types of bearings or seals, can be added to the code."_

**Comment by nnadeau** [comment]
@raphaeltimbo please link the PR/commit that adds this statement. Do you have examples of adding new bearings or seals?

**Comment by raphaeltimbo** [comment]
Hi there @nnadeau !
I had accidentally removed the line when changing the explanation for modeling assumptions.
On #515 I have added the mentioned text and also examples on how to add new bearings.
Let me know if you have more comments.

**Comment by nnadeau** [comment]
@raphaeltimbo thanks for the examples, but I wouldn't necessary add the python code to the paper (JOSS likes short papers and the code makes it verbose).

I'd recommend removing the python examples but keeping your updated statements: 

```
ROSS is extensible and new elements, such as different types of bearings or seals, can be added to the code. As anexample, one can add a class for a tapered roller bearing by inheriting from `BearingElement`:

Other elements that require more customization can be added by inheriting directly from `Element`, in this case it isnecessary to implement the required methods that should return the element's mass, stiffness, damping, and gyroscopicmatrices:
```

just reformulate the above statements to not target "in-paper examples", but rather the examples you've included in the repo

**Comment by raphaeltimbo** [comment]
I have removed the Python code from the paper and added a mention to the `BallBearingElement` that we have already implemented and is available in the repo (commit 
7298d94).

**Comment by raphaeltimbo** [comment]
I have modified the text to avoid repeating 'an example' ( commit 6e28f4d9a6915d355583eca4b25825b210ec3d54).
The text now is:

> ROSS is extensible and new elements, such as different types of bearings or seals, can be added
> to the code. As an example, one can add a class for a tapered roller bearing by inheriting
> from BearingElement. The implementation of the BallBearingElement in our code uses
> this strategy.
> Other elements that require more customization can be added by inheriting directly from
> Element, in this case it is necessary to implement the required methods that should return
> the element’s mass, stiffness, damping, and gyroscopic matrices.

**Comment by nnadeau** [comment]
@raphaeltimbo looks good. Nitpick from me: repeated use of `as an example` two sentences in a row

```
ROSS is extensible and new elements, such as different types of bearings or seals, can be added to the code. As an 
example, one can add a class for a tapered roller bearing by inheriting from `BearingElement`. As an example we have 
the implementation of the `BallBearingElement` in the code.
```

**Comment by nnadeau** [comment]
i see you caught that already in https://github.com/ross-rotordynamics/ross/commit/6e28f4d9a6915d355583eca4b25825b210ec3d54

**Comment by nnadeau** [comment]
:+1: fixed in https://github.com/ross-rotordynamics/ross/commit/6e28f4d9a6915d355583eca4b25825b210ec3d54 and https://github.com/ross-rotordynamics/ross/commit/7298d94214d16526fbb3d716ee79b2dc1a8e6bc4
