### ISSUE TITLE
Pip install "ross..." misses a file

### ISSUE THREAD

**Issue by CisneirosRaphael** [ross-rotordynamics/ross#497]
Today I updated the last ross version, done the pip install ross-rotordynamics. However, when I tryed to run the tutorial on the class material I noticed that the new_units.txt file was missing.

**Comment by rodrigomoliveira1** [comment]
We have released a new version (0.3.0) but we didn't update the pypi version.
Meanwhile, try using `pip install git+https://github.com/ross-rotordynamics/ross.git`.

**Comment by verg1lio** [comment]
@rodrigomoliveira1 Thanks for the tip, this solved the issue.
