### ISSUE TITLE
Installation/tutorial error

### ISSUE THREAD

**Issue by verg1lio** [ross-rotordynamics/ross#499]
Hi, and good afternoon! It's Vergilio from LMEst here.

I believe there is a file missing, or with a wrong name, when running ROSS. The error message i'm getting is:

>>> import ross as rs
Traceback (most recent call last):
  File "C:\Users\Vergilio\AppData\Local\Programs\Python\Python37\lib\site-packages\pint\registry.py", line 524, in load_definitions
    with open(file, encoding="utf-8") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Vergilio\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\ross\\new_units.txt'

This is running on VS Code on a 64bits Win10 PC. The Python version used was 3.7.7 64bits. This "new_units.txt" code does not seem to have been downloaded in the installation, although there is a similar "units.py" code in the ross subfolder.

**Comment by rodrigomoliveira1** [comment]
Hello @verg1lio, thanks for the comment.

We are aware of this problem. It's the same Issue than #497. I've posted an alternative to solve it.

So, I'm closing this one. If there's any other problem related to the installation, comment on #497 so we can track it better,
