### ISSUE TITLE
Create objects, attributes, methods and UML diagram

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#5]
Create objects, attributes, methods and UML diagram.

**Comment by GabrielBachmann** [comment]
I also included the original XML file that can be edited in case there is any change of course in the project's design, and a HTML version, on the google drive project folder.

![rotordynamics-ross 4 1](https://user-images.githubusercontent.com/32821252/50386686-131c5200-06d3-11e9-9806-f5746295be81.png)

**Comment by raphaeltimbo** [comment]
@GabrielBachmann, this is looking good. What tools did you use to build the diagram?
I think we can put the .xml file in the `ross/doc/` folder for now. Could you add the file and open a pull request?

**Comment by GabrielBachmann** [comment]
I've put the .xml file in the doc folder. The tool used to build this diagram is avaible on www.draw.io
The license terms were checked, as you can see in this link: 
https://desk.draw.io/support/solutions/articles/16000042494-what-are-the-usage-terms-for-diagrams-produced-by-draw-io-

**Comment by raphaeltimbo** [comment]
I will be closing this issue for now. We can reopen it if needed.
