### ISSUE TITLE
Magnetic bearing - add tests

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#509]
@davidjgm, now that MagneticBearing class is created, we should add some tests to ensure its correct functioning.

You can add it in `ross/tests/test_bearing_seal_element.py` file.
Check how it's done to other classes and make something similar.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
Is this still an issue? @rodrigomoliveira1 @davidjgm

**Comment by davidjgm** [comment]
I have not add the tests yet. I will add them as soon as possible.
