### ISSUE TITLE
Adapt ross.Rotor class to 6 dofs elements

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#526]
As the implementation of the 6 dofs elements has advanced, we need to adapt the `Rotor` class from rotor_assembly.py to receive these new elements, as well as the methods that run the analyses.

Many methods need to recognize the number of degrees of freedom per element, and, untill now, there is no option to set different values from 4 or 2 dofs (4 for shaft elements; 2 for bearing and disk elements).

We could add to `.__init__()` a piece of code to check what type of element the user is inputting, and then, set an attribute that is carried to every method which needs to verify the number of dofs per element or node.

Moreover, the code needs to check the consistence of the elements. If elements with different values for dofs are added to the rotor, it should raise an error.

**Comment by verg1lio** [comment]
Hello @rodrigomoliveira1 , this methodology coherence testing has been placed directly on the rotor_assembly, in order to automate the operation. We simply inform the user about it if there is an inconsistency present, otherwise it should go unnoticed.
