### ISSUE TITLE
Rotordynamic Report - Presenting analyses in the report

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#534]
The report under construction returns the analysis following the API standards, This means it presents the analyses required by the standard.

For now, the api_report.py returns, in this following order (for minimum and maximum bearing clearance):
- Undamped critical speed map
- Mode shapes
- Unbalance response
- Stability level 1
- Stability level 2 (if needed)
- A summary of results

As our report is not completed strict to follow only the API requirements, but it's intended to present other results, we could set a list of other analyses to complement out report.

For example, we could incluse do a list like this one below (considering ROSS capabilities):
- Static analysis
- Undamped critical speed map
- Campbell Diagram
- Mode shapes
- Unbalance response
- Orbit response
- Stability level 1
- Stability level 2 (if needed)
- A summary of results

I'd like some other suggestions to add to the report.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by GabrielBachmann** [comment]
I think we should move this issue to ross-report repository
