### ISSUE TITLE
Maybe we should remove isort

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#538]
I don't know if we are getting many benefits from isort.
We had some problems trying to run it with black, and I don't think this is a task that needs to have this kind of automation on the CI. 
I think it would be better to remove the requirement and from time to time we organize our imports locally and update the code.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
It looks like the new isort version (5.0) will have an option to run:
`isort --profile black` 
This will configure some settings (e.g. `multi-line=3`) so that will run in a compatible way with black.
