### ISSUE TITLE
Remove API name from report

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#541]
We should remove the API name from the report module (API_Report -> report) and also make the report more general so we can apply criteria from different standards.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
@GabrielBachmann , can you take a look at this one?

**Comment by GabrielBachmann** [comment]
Sure, when we have a new version of the Report I'll remove it!

**Comment by rodrigomoliveira1** [comment]
I think we should move the Report folder inside ross folder.
Then, move the api_report.py file inside Report folder. So we can keep everything related to it in the same place

**Comment by GabrielBachmann** [comment]
Right now, in my remote repository there's not a API_Report folder.
The report.py file substitutes former api_report.py and there's a folder called assets in the ross.__file__ folder. 
Do you guys think that's ok, or should I create a Report folder to put assets and templates inside of it?

**Comment by rodrigomoliveira1** [comment]
I think it's better to put this "assests" folder inside a "Report" folder, because as we're adding some new files and contents to this feature, it'll be more organized.

**Comment by GabrielBachmann** [comment]
@rodrigomoliveira1 do you think that's good, or should I put report.py inside the report folder too? ![image](https://user-images.githubusercontent.com/32821252/86159387-a6142480-bae0-11ea-8c3f-f54c161af464.png)
