### ISSUE TITLE
Polar plot for forced response analysis

### ISSUE THREAD

**Issue by atbrandao** [ross-rotordynamics/ross#553]
The Bode plot (amplitude and phase) should provide an option to be shown in its Polar form.

In cases for which the excitation does not clearly excites a certain critical speed, the polar form of the Bode Plot can be very helpful to identify the critical speed passing.

**Comment by rodrigomoliveira1** [comment]
When plotting unbalance response or frequency response, it'll be returned this format:

![image](https://user-images.githubusercontent.com/45969994/82911061-ce3cc080-9f41-11ea-8a04-0cdae514d0ab.png)

**Comment by atbrandao** [comment]
Perfect!
The example shown generates a weird polar plot because of the low damping of the first critical. But that's exactely what I had in mind. Thanks!
