### ISSUE TITLE
Ross-website link to source broken

### ISSUE THREAD

**Issue by GabrielBachmann** [ross-rotordynamics/ross#560]
When trying to open source on ross-website, it links to this [page]( https://ross-rotordynamics.github.io/ross-website/_sources/examples.rst.txt)

**Comment by GabrielBachmann** [comment]
![Uploading image.png…](This is the button mentioned above.)

**Comment by GabrielBachmann** [comment]
This is image shows the button mentioned above.
![This is the image mentioned above](https://user-images.githubusercontent.com/32821252/82356016-67675680-99d9-11ea-85bd-317a745c088a.png)

**Comment by raphaeltimbo** [comment]
Hi there @GabrielBachmann !
I think this is actually the correct behavior, it shows the .rst file for that page.
To check the html generated you could use:
view-source:https://ross-rotordynamics.github.io/ross-website/examples.html

**Comment by GabrielBachmann** [comment]
Oh sorry about that, I confused API and Source buttons!
