### ISSUE TITLE
Move "sparse" argument to run_modal()

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#583]
Following @raphaeltimbo idea of moving `n_eigen` from `Rotor.__init__()` to  `Rotor.run_modal()` (Issue #573), I'd like to propose the same to `sparse` argument. It's used only when running the modal analysis, solving the eigenvalues / eigenvectors. And as this argument is called only to define what numpy/scipy method to call when running the modal analysis, I think it makes sense to move `sparse` to `run_modal()`. 

What do you think?

**Comment by raphaeltimbo** [comment]
Totally agree with that.

**Comment by rodrigomoliveira1** [comment]
PR #588 closes this issue.
