### ISSUE TITLE
Create choices in internal radius function in fluid flow and make them user friendly

### ISSUE THREAD

**Issue by flaviorangel** [ross-rotordynamics/ross#59]
The rotor radius is being calculated arbitrarily. The user must be able to choose which structure they want for the rotor radius. This choice should be done when the object is instantiated in the form of a parameter the user will give, if they so wish.

**Comment by raphaeltimbo** [comment]
Hi @flaviorangel !
Could you give more details about the possible structures that the user can choose?

**Comment by flaviorangel** [comment]
By structure I meant geometry of the rotor. The geometries presented in Luiz Queiroz's undergraduate dissertation are cylindrical, sinusoidal, conical, and square. When instantiating the class, the user should be able to choose among geometries. A more advanced version could let the user give their own customized geometry as a parameter.

**Comment by raphaeltimbo** [comment]
Got it! But I don't know if all these geometries would make sense for our case. 
I remember that the dissertation that you have cited had some parts related to drilling, and I am wondering if these different geometries would not be more related to that context.
Maybe we should check if all those options are really needed.

**Comment by flaviorangel** [comment]
I agree. Let us discuss the issue in our next meeting.

**Comment by flaviorangel** [comment]
This issue should be closed and reopened when it is a better moment to be implemented, since it is an advanced feature and don't relate to the tests we are doing now. We are lacking a label to identify such issues.

**Comment by raphaeltimbo** [comment]
I have just created a label "wontfix for now".
