### ISSUE TITLE
Rotordynamic Report - Standard texts file

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#605]
The report is supposed to bring some discussions to the analyses and results. 
Following the idea of autorunning the report, the texts strings must be automatic too, and I think the best way to bring it to the report is on a separated file.

Each method from class `Report` could have a matching method in this new file, so we organize better the results and its respective text string.

Any other ideas of how doing it?

**Comment by GabrielBachmann** [comment]
I think we can get an jija2 html template file with all texts

**Comment by rodrigomoliveira1** [comment]
I'm closing this Issue. We can track it where it's mentioned above.
