### ISSUE TITLE
Units support

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#609]
ROSS has only some small support for units implemented with the `check_units` decorator.
This decorator will verify each argument name and convert to units declared in the units.py module and then it will return the converted values to the function. 
The returned values are of the same type as the original argument (float or int), and are not of the pint.Quantity type. This is because after converting with pint.Quantity we only pass the magnitude attribute.
Ideally we would have pint.Quantity objects passed and everything would have a magnitude/unit attached to it, so when creating a material the user could run things like:
```python
import ross as rs

Q = rs.units.Q
steel = rs.Material(name='steel', rho=7810, E=Q(3e7, 'psi'), G_s=Q(1e7, 'psi'))

print(steel.E)
206842721646.701 N / m2
print(steel.E.to('lbf/inch**2'))
30000000.0 lbf / in2
print(steel.rho.to('lb/ft**3'))
487.56237209968947 lb / ft3
```

I have tried to implement this approach here https://github.com/raphaeltimbo/ross-1/tree/improve-pint but I had some problems.
1. Working with arrays and units in our case is not trivial. Take, for example, the disk mass matrix:
```python
M = np.array([[m, 0,  0,  0],
              [0, m,  0,  0],
              [0, 0, Id,  0],
              [0, 0,  0, Id]]
```
Here `m` has units kg and `Id` kg*m**2, so it is not possible to assemble a `Quantity` array in this case.
So we will have to use the Quantity magnitude to construct the array:
```python
m = m.magnitude
Id = Id.magnitude
M = np.array([[m, 0,  0,  0],
              [0, m,  0,  0],
              [0, 0, Id,  0],
              [0, 0,  0, Id]]
```
The problem with this is that we kind of defeat the purpose of having Quantity objects passed to these functions if we have to fall back to using their magnitude all the time.
2. Other modules depending on ROSS main modules would have to adapt to expect Quantity objects. For example, the following test for the sthocastic module fails with this code:
```python
def test_st_shaft_element(rand_shaft):
    elm = list(iter(rand_shaft))
    assert [sh.L for sh in elm] == [1.0, 1.1]
    assert [sh.idl for sh in elm] == [0.01, 0.02]
    assert [sh.odl for sh in elm] == [0.1, 0.2]
    assert [sh.idr for sh in elm] == [0.01, 0.02]
    assert [sh.odr for sh in elm] == [0.1, 0.2]
    assert [sh.material.E for sh in elm] == [209000000000.0, 211000000000.0]
```
Result:
```python
Expected :[1.0, 1.1]
Actual   :[<Quantity 1. m>, <Quantity 1.1 m>]
```
Using Quantity everywhere will also add some extra computing time.

So, considering that, I think it is not worth for our package to have pint 'fully' implemented.
We could keep working with the unit conversion in the input and we could also add some utility functions to help the user converting the final results and also plotting with the desired units.
Internally, however, we would keep working with normal arrays/floats.

I will start to implement something and will send updates here for some feedback.

**Comment by rodrigomoliveira1** [comment]
The way I see it, It's ok to have units conversion for inputs and outputs only.

The input units are automatically converted to the SI, and ROSS runs this way. Finally, when post-processing results, the user chooses the units to be displayed at graphs.
