### ISSUE TITLE
isort not working properly

### ISSUE THREAD

**Issue by GabrielBachmann** [ross-rotordynamics/ross#610]
In PR #606 I'm getting this error log by travis
![image](https://user-images.githubusercontent.com/32821252/86314169-5a0ad200-bbfd-11ea-82e2-8fdd5f459093.png)
I've even tried to clone my remote repository again the report.py file was not changed.
![image](https://user-images.githubusercontent.com/32821252/86314095-2465e900-bbfd-11ea-9adf-cf2c3c477f44.png)

**Comment by rodrigomoliveira1** [comment]
Try `isort --recursive ross` and run It with ross folder

**Comment by GabrielBachmann** [comment]
isort was not working properly on my computer and @rodrigomoliveira1 helped me running it for me, I'm closing this issue.
