### ISSUE TITLE
AppVeyor not working 

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#611]
AppVeyor CI has not been working properly lately.
This message is appearing in every commit we have done recently.

![image](https://user-images.githubusercontent.com/45969994/86365506-f9f14b80-bc4f-11ea-8ddb-de97172b6c9e.png)

The [build](https://ci.appveyor.com/project/raphaeltimbo/ross/builds/33602334) which began to fail.

**Comment by rodrigomoliveira1** [comment]
I found a suggestion saying GitHub authorization is the most probable reason for this. since we did not change anything in appveyor.yml recently. Maybe appveyor.yml cannot be read. So, re-authorizing GitHub at https://ci.appveyor.com/account, should help.

**Comment by raphaeltimbo** [comment]
I have tried this now and restarted the last build. Lets see if it works.

**Comment by rodrigomoliveira1** [comment]
It works. 
But now we have to raise another Issue about appveyor and the temp files used to test the save methods. I think appveyor is not dealing well with them

**Comment by raphaeltimbo** [comment]
I have reopened #590 to work on this.
