### ISSUE TITLE
Move API_Report folder and files to ROSS_Report repository

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#633]
ROSS repository won't store the files corresponding to the rotordynamic report anymore, as it's explained in Issue #620.
We should move the API_Report folder (which we have discussed to be renamed) from this repository and to [ross_report](https://github.com/ross-rotordynamics/ross-report).

I think PR #613 should be closed and re-opened on ross_report too.

**Comment by GabrielBachmann** [comment]
I think there's no need for reopening PR #613 on the report repo, all the changes are already included in the report repository!
