### ISSUE TITLE
Tutorial - texts with docstrings

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#637]
In our tutorial we have several cells in markdown that have the docstring for a function in it. Example:
![image](https://user-images.githubusercontent.com/18506378/88574038-0a5ed100-d018-11ea-8462-e617a8bd1195.png)

One problem that this can cause is that we have to update these cells by hand if we change some docstring, eventually we will miss some updates.

The other problem that I see here is that our tutorial seems very long because we are putting these texts in lots of places.

Another point is that, since the tutorial is in a jupyter notebook, it is very easy to the user to get the documentation with `?` or <shift + tab> inside the parenthesis, so I don't think we gain much by writing everything again in a cell.

So, I would like to propose that we remove these docstrings in the tutorial.

**Comment by rodrigomoliveira1** [comment]
I'm working on these changes. By the way, without the docstrings, users will need to access the API page on ROSS' website, so they get a complete information.
With that in mind, I'd suggest we add other files to the API page, like point_mass.py, results.py, fluidflow module and stochastic module.

**Comment by rodrigomoliveira1** [comment]
PR #653 closes this issue.
