### ISSUE TITLE
Accessing object memory address

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#67]
I've been trying to access the bearings' stiffness coefficients ('kyy') from this pandas dataframe shown below.

`df_bearings = pd.DataFrame([el.summary() for el in self.bearing_seal_elements])`

I'm using this code line 
`self.df_bearings.loc[i, 'kyy']`

but it returns its memory address instead of its value
`<bearing_seal_element._Stiffness_Coefficient object at 0x000002330DC8F128>`

How could I get the "kyy" value from the dataframe then?

**Comment by GabrielBachmann** [comment]
using self.df_bearings.loc[i, 'kyy'].coefficient should solve this issue.

**Comment by rodrigomoliveira1** [comment]
Thank you, @GabrielBachmann! It works just fine
