### ISSUE TITLE
Split tutorial

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#673]
Our tutorial now is very long and it is slow to load in the website.
I think it would be better if we split the tutorial in two parts: 

1. Building the model;
2. Running the analysis.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
