### ISSUE TITLE
Deflected shape plot layout

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#675]
The deflected shape 3d plot does not have enough space in the current layout:
![image](https://user-images.githubusercontent.com/18506378/93924233-d7b91800-fcea-11ea-90e0-084046f6d754.png)

Maybe we could move the legend to below the plot, like we have in the Campbell diagram.

**Comment by rodrigomoliveira1** [comment]
Like this one:

![newplot(3)](https://user-images.githubusercontent.com/45969994/94006719-a554fc80-fd76-11ea-8726-87e8c5a11475.png)

**Comment by rodrigomoliveira1** [comment]
The overlapping labels remais an issue. A simple solution is setting a default size for this figure (800px x 600px - 4/3 ratio).
The figures gets slightly larger but has a much better layout.

![newplot(7)](https://user-images.githubusercontent.com/45969994/94007522-f6192500-fd77-11ea-8379-e2e07333bdea.png)

I tried doing 640px x 480px, but it didn't fit well.

![newplot(5)](https://user-images.githubusercontent.com/45969994/94007800-5dcf7000-fd78-11ea-9b76-40de36b724e6.png)

**Comment by rodrigomoliveira1** [comment]
I did some domain and camera work to set a better viewpoint to the 3D plot

![newplot](https://user-images.githubusercontent.com/45969994/94016295-4f875100-fd84-11ea-98d5-ba32bd10203d.png)

**Comment by rodrigomoliveira1** [comment]
PR #676 closes this issue.
