### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'numpy.float64'

### ISSUE THREAD

**Issue by nilswagner** [ross-rotordynamics/ross#693]
File "example2.py", line 120, in <module>
    show(rotor_list[0].plot_rotor(plot_type='matplotlib'))
  File "/home
[example2.py.gz](https://github.com/ross-rotordynamics/ross/files/5416940/example2.py.gz)
/wagner/git/ross/ross/rotor_assembly.py", line 1814, in plot_rotor
    step = disk.scale_factor * mean_od
TypeError: can't multiply sequence by non-int of type 'numpy.float64'

**Comment by rodrigomoliveira1** [comment]
Hello @nilswagner! Thank you for reporting this issue. 
Could you inform us the ROSS version you are using? We have released version 0.4.1 a couple of weeks ago, fixing some problems regarding to examples (that were out to date).

By the command you are informing `show(rotor_list[0].plot_rotor(plot_type='matplotlib'))` I assume you are using version 0.3 or 0.4.0. 

If it's the case, try updating the package by using `pip install ross-rotordynamics -U`

Tell us if there's anything we could help you out.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
I am assuming everything is ok here, so I am going to close the issue.
Feel free to reopen it.
