### ISSUE TITLE
Add major and minor axis in response plots

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#714]
As mentioned by @leoishimoto in #710:

> The major and minor axis of the ellipse is highly desirable not only the probes reference. In circular orbits does not make difference but for anisotropic bearings is necessary.

@rodrigomoliveira1, you have mentioned that you are already working on a solution for this one, so I am going to assign you here.

**Comment by rodrigomoliveira1** [comment]
As requested by @LeifParr, 

> Another comment regarding the response plotting, is that the plots should indicate the node number (and the label) which are plotted. As far as I can see, there is no option to label probes, so there is room for confusion about what is being shown. If you consider this an important issue, you can move this into a new issue.

I'm including optional tags to name `probes` and the node number. If the probe tuple has only 2 items (node and orientation), the tag is set to a default name, like it was previously ("Probe 1", "Probe 2", etc)
Example:

```python
>>> rotor = rs.rotor_example()
>>> speed = np.linspace(0, 1000, 301)
>>> response = rotor.run_unbalance_response(
...                                         node=3,
...                                         unbalance_magnitude=0.001,
...                                         unbalance_phase=0.0,
...                                         frequency=speed)

>>> # POST-PROCESSING
>>> # Get results from node 3 with 90° orientation
>>> probe_node_1 = 3
>>> probe_angle_1 = np.pi / 4

>>> # Get results from node 3 for major axis
>>> probe_node_2 = 3
>>> probe_angle_2 = "major" # here we insert the string "major" to get the major axis values

>>> # Get results from node 3 for minor axis
>>> probe_node_3 = 3
>>> probe_angle_3 = "minor" # here we insert the string "minor" to get the minor axis values
>>> response.plot_magnitude(probe=[
...     (probe_node_1, probe_angle_1),
...     (probe_node_2, probe_angle_2, "My Tag 1"),
...     (probe_node_3, probe_angle_3, "My Tag 2"),
... ], yaxis=dict(type="log"))
```
![image](https://user-images.githubusercontent.com/45969994/101013374-f2a5d500-3542-11eb-8b30-3b44f01a1482.png)
