### ISSUE TITLE
Include rotor speed on mode shape plots

### ISSUE THREAD

**Issue by LeifParr** [ross-rotordynamics/ross#718]
![Mode_Shape_Example](https://user-images.githubusercontent.com/74429840/101495894-642dbb00-3969-11eb-83d3-a59ed86c2e77.png)

Considering how plotting of mode shapes is done in other rotordynamic program, here are some points which could be improved:
- Add possibility for custom title. For some of the other plots, I have added a title manually, but I'm not sure if this is straight-forward here, as the title field is used for vital info.
- Add the rotor speed. This is in my opinion essential, as the mode shapes may be plotted for several speeds, and we quickly loose track if the rotor speed isn't plotted per default.
- We use damping ratio, and I do not see a way to select damping ratio. 
- Contrary to the campbell diagram, I do not see a way to choose between Wn and Wd  for the natural frequency.

Anyway, this was only some suggestions, so far I do enjoy working with the ROSS module

**Comment by rodrigomoliveira1** [comment]
Hello, @LeifParr, we're glad you're enjoying working wih ROSS so far. Thanks again for your suggestions, it's important to us to have this feedback.

![image](https://user-images.githubusercontent.com/45969994/101503067-7a7b4d00-3950-11eb-8bd2-e4c8652fe81a.png)


So, answering your topics:
>Add possibility for custom title. For some of the other plots, I have added a title manually, but I'm not sure if this is straight-forward here, as the title field is used for vital info.

- We can add an argument to users input a breif title, more like a tag, as you can see in the figure above (ref 1). It's also possible to overlay the original title layout inserting the kwarg `title_text`, thus, you completely make your own title for the plot. This is, actually, a feature from [Plotly](https://plotly.com/python/reference/layout/) (link to the layout API reference). We only take advantage of this to allow the user to manipulate the `Plotly.Figure.layout` by inserting `kwargs`. Examples:

```python
>>> # Add fast title tag
>>> import ross as rs
>>> rotor = rs.rotor_example()
>>> modal = rotor.run_modal(speed=200)
>>> modal.plot_mode_3d(0, title="Rotor Model")
```
![image](https://user-images.githubusercontent.com/45969994/101505740-71d84600-3953-11eb-8cf9-87e1a365761d.png)


```python
>>> # Modifying title template 
>>> import ross as rs
>>> rotor = rs.rotor_example()
>>> modal = rotor.run_modal(speed=200)
>>> fig = modal.plot_mode_3d(1, title_text="NEW TITLE HERE")
```
![image](https://user-images.githubusercontent.com/45969994/101505972-a946f280-3953-11eb-97d4-e8e6e16d81fb.png)


> Add the rotor speed. This is in my opinion essential, as the mode shapes may be plotted for several speeds, and we quickly loose track if the rotor speed isn't plotted per default.

- Added as seen in ref. 2 (first figure).

> We use damping ratio, and I do not see a way to select damping ratio.

- Added as seen in ref. 4 (first figure).

> Contrary to the campbell diagram, I do not see a way to choose between Wn and Wd for the natural frequency.

- We're adding an argument (`frequency_type` - same argument that `run_campbell` has) to `plot_mode_3d` and `plot_mode_3d` to select what frequency to display. You can choose between "wd" and "wn". Example:

```python
>>> import ross as rs
>>> rotor = rs.rotor_example()
>>> modal = rotor.run_modal(speed=200, sparse=True)
>>> # Display damped natural frequency value
>>> modal.plot_mode_3d(1, frequency_type="wd", title="Rotor Model")
>>> # Display undamped natural frequency value
>>> modal.plot_mode_3d(1, frequency_type="wn", title="Rotor Model")
```

**Comment by LeifParr** [comment]
Excellent. I trust you will also implement this for the 2d mode shape plots.
