### ISSUE TITLE
Bug in rotor.summary using rotor tag

### ISSUE THREAD

**Issue by LeifParr** [ross-rotordynamics/ross#720]
I think I accidentally discovered a little bug, which should be a quick one to fix.
When initalizing a rotor using the tag = 'Some_tag', there is no error in the rotor init.
But when trying to plot the rotor-summary, e.g. rotor.summary().plot(), I get the following error:
Traceback (most recent call last):
  File "C:\Leif\Python_L\Rotordynamics\Ross_Excel_Rotor_Oseberg.py", line 38, in <module>
    table=rotor591c.summary().plot()
  File "C:\Program Files\Python38\lib\site-packages\ross\rotor_assembly.py", line 2694, in summary
    self.tag,
AttributeError: 'Rotor' object has no attribute 'tag'

I looked through the code, it seems that the self.tag is only initialized when tag=None, there is no else case.

**Comment by rodrigomoliveira1** [comment]
This [commit](https://github.com/ross-rotordynamics/ross/pull/719/commits/e2919c46347ffc0323b3e964ec77d60754ff2378) should fix it.
