### ISSUE TITLE
Split make html and notebooks

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#724]
We should find a way of splitting the process of building the documentation based on notebooks from the part that depends only on .rst files. 
Sometimes we are editing only some lines in .rst and want to check the results fast, but building all docs with the notebooks is taking a lot of time.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
I have been trying to solve this but have not yet found a command where the notebook part will not be built.
Before we would use a script to build rst files based on the notebooks, now we are using nbsphinx.
I have added the `nbsphinx_execute = 'never'` to the conf.py file, but it still takes a long time to build the docs.
I have also tried to exclude the examples from the build by using the sphinx `exclude_patterns` option, but had no success. 
I am also trying to use the `.. only::` directive, but it looks like we can only use this directive in parts of a text, not to exclude sections (I wanted to exclude the examples section).

**Comment by raphaeltimbo** [comment]
We actually had to add `nbsphinx_execute='always'` in our conf.py file (see #760).
If we want to build the docs without running the notebooks we can do:
`make NBSPHINX_EXECUTE='never' html`

Although reading the sources already consumes a lot of time. 
But I think we cannot improve on that, so I am going to close this as soon as the PR is merged.
