### ISSUE TITLE
Migrate from TRAVIS CI to a new Testing CI.

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#738]
If you have noticed in recent PR, TRAVIS CI hasn't been testing anything we have uploaded.
Then, I've been looking for the source of this problem, and look what is happening:

![image](https://user-images.githubusercontent.com/45969994/104464200-6c44d000-5591-11eb-9ec2-c3d8b1907122.png)

You can't see it right, but in the last column, it says that our repository does not have enough credits. 
Doing some quick research, I just found out that Travis CI announced new pricing model, effectively ending open source offering, and Travis-ci.org will be put into read-only mode.

Actually, there's still and free option to use TRAVIS, but we need to migrate from travis-ci.org to travis-ci.com.

Here is a [guide](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions) to help us fixing this issue.

**Comment by rodrigomoliveira1** [comment]
When migrating to travis-ci.com, we need to assign to one of their "plans". The free one limits the number of builds you can run, until you need to purchase more credits to keep using travis. 

![image](https://user-images.githubusercontent.com/45969994/104467428-13773680-5595-11eb-95cf-cd50133c6957.png)


![image](https://user-images.githubusercontent.com/45969994/104467687-62bd6700-5595-11eb-8dbe-5da6eeae30aa.png)

**Comment by raphaeltimbo** [comment]
@rodrigomoliveira1, as we were discussing, I think the option you were talking about with GitHub Actions is one that we should really evaluate. 
I have also seem a lot of projects migrating there, and we would have more things in one place only (github).
Also, I think github is more 'stable' in the sense that we probably won't have to this kind of migration again in a near future.

**Comment by rodrigomoliveira1** [comment]
@raphaeltimbo, I'm doing a first try with GitHub Actions. I've just commited this [new file](https://github.com/ross-rotordynamics/ross/blob/master/.github/workflows/test.yml) to run our tests.
I'm starting with the simple, only adding pytest. We can also add codecov, black and Isort by different workflow files. It doesn't need to be all in one.

**Comment by raphaeltimbo** [comment]
I am just reopening this for a last discussion about appveyor.
Since github actions are also testing windows builds, maybe we could remove the appveyor check?
I do not see any advantages using appveyor now. What do you think @rodrigomoliveira1 ?
If this is the case I will do a PR removing appveyor and also some files related to appveyor and travis ci.

**Comment by rodrigomoliveira1** [comment]
I fully agree.
