### ISSUE TITLE
Tutorials link is broken

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#748]
This link here is not working:
![image](https://user-images.githubusercontent.com/18506378/106485387-4ffcca80-648f-11eb-929b-a4d5e1c18763.png)

**Comment by rodrigomoliveira1** [comment]
This [commit](https://github.com/ross-rotordynamics/ross/pull/746/commits/036b53545fa72572581b3245b6585b6c3707ab33) should fix it.
