### ISSUE TITLE
Bugs when converting notebooks to html - Fluid Flow Examples

### ISSUE THREAD

**Issue by JuliaMota** [ross-rotordynamics/ross#749]
There are some bugs in the Fluid Flow theory documentation registered on the ROSS website regarding equations described in the text. The errors are not shown in Jupyter Notebook, but appeared on the website when converting to HTML format.

Below is an example of what is happening.

![image](https://user-images.githubusercontent.com/39375523/106615220-f8bc3000-654a-11eb-91c1-ba0f9892fdc1.png)

**Comment by rodrigomoliveira1** [comment]
For a matter of registration, those bugs happen when we add a blank space between the formulas and the `$` icon, for example:

```latex
where $\rho$ is the specific mass of the fluid, $\mathbf{v}$ is the velocity field, 
and $\sigma=-p \mathbf{I} + \tau $
```

This blank space between `\tau` and `$`, at the end of the line, was responsible for breaking the entire line compilation. So, we should always do it without spaces:

```latex
where $\rho$ is the specific mass of the fluid, $\mathbf{v}$ is the velocity field, 
and $\sigma=-p \mathbf{I} + \tau$
```
