### ISSUE TITLE
Create automatic report

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#77]
Generate a report with the main results from the rotordynamic analysis.
Some criteria should be used to state if the report is ok according to a standard.

**Comment by rodrigomoliveira1** [comment]
Thinking about it, maybe we could create a new file to do this analysis according to the standards and then generate a report. But first of all, we should work in this new file, what you think?

**Comment by raphaeltimbo** [comment]
I agree that creating a file to do the analysis is the first step.
We can worry about creating the actual report later. For reference, I saw [this blog post](https://pbpython.com/pdf-reports.html).

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
We have a PR open to solve this issue (#427).

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by rodrigomoliveira1** [comment]
PR #427 has been merged and closes this issue.
