### ISSUE TITLE
Improvement on method .plot_rotor() 

### ISSUE THREAD

**Issue by CisneirosRaphael** [ross-rotordynamics/ross#780]
When you use .plot_rotor the model displays same size disks even the values mass/inertia/diameters being different.

It makes validation a bit harder if the user gives any wrong input.
My recommendation is to plot proportionaly different disks sizes with regard to mass/inertia or diameters.

**Comment by rodrigomoliveira1** [comment]
Hello @CisneirosRaphael. Thank you for your feedback!

While we do not have such feature, I'd recommed you to use `scale_factor` argument to scale the glyph size. Check [DiskElement API](https://ross-rotordynamics.github.io/ross-website/generated/elements/ross.DiskElement.html#ross.DiskElement). 
Setting `scale_factor` smaller than 1, reduces the glyph size, and setting it greater than 1, inreases its size. You can set each `scale_factor` proportionaly to their masses/inertia manually.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
Hi @CisneirosRaphael !
I have changed the code to allow the following when creating disks:
```python
disk = DiskElement(n=0, m=32, Id=0.2, Ip=0.3, scale_factor='mass')
```
If you create a rotor were all disk elements hava `scale_factor='mass'`, the code will calculate automatically calculate a scale factor based on the disk mass.

**Comment by raphaeltimbo** [comment]
> Hello everyone, I am new working with this tool, but I would like to ask a question: when I use .plot_rotor() command, what I obtain is a squeezed text of hundred of lines, insted of a plot. I do have available plotly lib, but I do not know exactly what is happening. I would really appreciate if someone could help me with this issue. Thank you in advance!

Hi @Maite2707.
I can look at your problem.
Please, if you could open a new issue and provide code to reproduce your problem and also a figure from the plot you are getting.

**Comment by Maite2707** [comment]
Hi Raphael,

Thank you for your answer. I opened a new issue:
https://github.com/ross-rotordynamics/ross/issues/891

Thank you for your support!
