### ISSUE TITLE
trouble with plotting campbell diagram

### ISSUE THREAD

**Issue by GitDiscipline** [ross-rotordynamics/ross#786]
import numpy as np
import ross as rs

r = rs.rotor_example()
speed_range = np.linspace(0, 1000, 100)
campbell = r.run_campbell(speed_range)
campbell.plot(harmonics=[0.5, 1])

this is the code I have used according to the ROSS documentation. But after running the code, no plot is seen. There is  no syntax or semantic error. Please help

**Comment by raphaeltimbo** [comment]
Hi there @GitDiscipline !
Are you running your code in a jupyter notebook or in an IDE?

The issue #733 also has some discussion about this that could help you.

**Comment by GitDiscipline** [comment]
Hi @raphaeltimbo 
      I  am using IDLE.  #733 has helped me.  Adding  .show()  resolved the issue
 
Thanks!

**Comment by raphaeltimbo** [comment]
Great @GitDiscipline !
I will close this issue now. Feel free to reopen it if you have problems in the future.
