### ISSUE TITLE
Fix - Coriolis Matrix Corrrection

### ISSUE THREAD

**Issue by marcelosamora** [ross-rotordynamics/ross#815]
Updating the matrix calculation method based on Lalanne and Friswell references. The new calculation method presents a more realistic representation of the physical phenomena.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
