### ISSUE TITLE
Error in cylindrical bearing when changing the number of volumes

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#819]
I have tried the following code:

```python
    bearing = THDCylindrical(
        L=0.263144,
        R=0.2,
        c_r=1.95e-4,
        n_theta=11,
        n_z=3,
        n_y=None,
        n_gap=1,
        betha_s=176,
        mu_ref=0.02,
        speed=94.24777960769379,
        Wx=0,
        Wy=-112814.91,
        k_t=0.15327,
        Cp=1915.24,
        rho=854.952,
        T_reserv=50,
        fat_mixt=0.52,
        T_muI=50,
        T_muF=80,
        mu_I=0.02,
        mu_F=0.01,
        sommerfeld_type=2,
    )
    bearing.run([0.1, -0.1])
```

But I am getting this error:
```
    
>       auxFx = auxP * vector_auxF_x
E       ValueError: operands could not be broadcast together with shapes (3,22) (23,)

../fluid_flow/cylindrical.py:800: ValueError
```

Here I have decreased the number of volumes in the `test_cylindrical.py` files from:
```python
        n_theta=41,
        n_z=5,
```
To:
```python
        n_theta=11,
        n_z=3,
```

Any idea on what is the problem here?

@verg1lio , @elyqg

**Comment by elyqg** [comment]
Hi @raphaeltimbo. I will check this problem and fix it. With the insertion of the pocket something was probably affected.

**Comment by raphaeltimbo** [comment]
Thanks @elyqg ! I will assign the issue to you.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
