### ISSUE TITLE
Argument `n` is not in the Bearing docstring

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#86]
As discussed on #79, the `n` argument is not explained in the `BearingElement` class.

- [x] Explain that `n` is the node in which the bearing will be located
- [x] Add example of use to the docstring

**Comment by rodrigomoliveira1** [comment]
I just did it and commited it in the PR #85.
Although this PR still have some issus in general (not related to this issue in particular).
