### ISSUE TITLE
Comparison of the natural frequency result of ROSS and ANSYS

### ISSUE THREAD

**Issue by WaCkySongs** [ross-rotordynamics/ross#885]
Hi, everyone,
  I'm studying the rotor dynamic with ANSYS and ROSS. I recently made a very simple benchmark test to compare the result of natural frequency of a shaft-beam (without any constrain or load). 
  However, the result shows big difference between ROSS (with 4DOF or 6DOF Timoshenko Beam) and ANSYS ( by default with BEAM189 ( 6DOF  timoshenko beam of 3-node quadratic element ) or SOLID).
  Could anyone please give me some information on the reason of it, i. e., why the natural frequency obtained by ANSYS(w7~=1600) is much smaller than those of ROSS (w7~= 9500) ?
 Is there any difference of the mass, stiffness matrix of the BEAM element in ANSYS?

  Here is the setting for the all tests:
            1. Material: steal by default.
            2. length/inner/outer diammeter of the shaft : 300/ 30.08/ 7 [mm] respectively
            3. shaft is discritized into 10 elements. 
            4. no constrain, load, rotational speed is applied
            
  Here is the result 
![image](https://user-images.githubusercontent.com/73467551/164852257-e336bf4f-0d76-4e64-a852-99ce0f22151f.png)

  Here is the code in ROSS  

```python
steel = rs.Material(name="Steel", rho=7850, E=210e9, Poisson=0.3)

nShaft = 10
nL = 0.3 / nShaft
d_in = 7e-3
d_out = 30.08e-3

shaft = [
    rs.ShaftElement6DoF(
    L=nL,
    idl=d_in,
    odl=d_out,
    material=steel,
    shear_effects=True,
    rotary_inertia=True,
    gyroscopic=False,
    )
    for _ in range(nShaft)
]
# print(shaft)

#% other
r1 = rs.Rotor(shaft)
modal = r1.run_modal(0,24)
print('natural frequencies',modal.wn)
print('damped natural frequencies',modal.wd)
```

**Comment by rodrigomoliveira1** [comment]
Hey @WaCkySongs! Thank you for doing such comparisons.

I believe both results are correct. The issue here is ANSYS returns the results in **HERTZ** unit, while ROSS returns the values in **RAD/S** as default.

So, if you converts ANSYS results to **rad/s**, you'll have `1536Hz * 6.28 (rad/s / Hz) = 9646 rad/s`, which is close enough to ROSS results.

Hope this helps!

**Comment by WaCkySongs** [comment]
Hi, @rodrigomoliveira1. 
Thanks so much for your reply. It was my mistake that I did not get the right Unit.
