### ISSUE TITLE
Implement simple hydrodynamic journal bearing

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#90]
Implement simple hydrodynamic journal bearing as described on Friswell's book considering:

- the flow is laminar and Reynolds’s equation applies
- the bearing is very short, so that `L/D << 1`, where `L` is the bearing length and `D` is the bearing diameter, which means that the pressure gradients are much larger in the axial than in the circumferential direction
- the lubricant pressure is zero at the edges of the bearing
- the bearing is operating under steady running conditions
- the lubricant properties do not vary substantially throughout the oil film
- the shaft does not tilt in the bearing

**Comment by flaviorangel** [comment]
We implemented an analytical and a numerical way to calculate pressure in fluid flow. The results are very close, but we still need to implement a test as well as define a tolerance. This is already a requirement in issue #37 thus I'm closing this issue.
