### ISSUE TITLE
PointMass class not listed in the API reference

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#900]
The PointMass class is not listed in the API reference.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
