### ISSUE TITLE
Errors in the misalignment tests

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#908]
For some reason two misalignment tests are now failing in the github actions:

```
ross/tests/test_misalignment.py ..........FF....
```

These are the `test_mis_angular_forces` and `test_mis_angular_forces_units`.
The tests are failing only with ubuntu and python 3.9:

![image](https://user-images.githubusercontent.com/18506378/195165468-4d67e26c-c4d9-442a-9979-81bc1dda8148.png)

We should check if this is just a problem of precision or if it is necessary to fix something in the code.

**Comment by marcusfilipesr** [comment]
Hello @raphaeltimbo! I'm going to look into this error. I'll get in contact with Izabela, to check and see what can be done to avoid this problem.
