### ISSUE TITLE
Fix toml saving routines

### ISSUE THREAD

**Issue by flaviorangel** [ross-rotordynamics/ross#91]
The saving routines are ignoring the values of some of the attributes of the elements, for example, in save_bearing_seal_element (rotor_assembly.py), we do:
`data[file_name[:-6]][str(element.n)] = { "n": element.n, "kxx": element.kxx.coefficient[0], "cxx": element.cxx.coefficient[0], "kyy": element.kyy.coefficient[0], "kxy": element.kxy.coefficient[0], "kyx": element.kyx.coefficient[0], "cyy": element.cyy.coefficient[0], "cxy": element.cxy.coefficient[0], "cyx": element.cyx.coefficient[0], "w": w, }`

**Comment by GabrielBachmann** [comment]
#92 closes this issue.
